-- Comprehensive GPS Store Products - Part 2
-- Adding products across all categories to reach 100+ items

-- Level Optik Products
INSERT INTO products (name, slug, description, short_description, sku, price, compare_price, cost_price, category_id, brand_id, is_active, is_featured, in_stock, stock_quantity, weight, dimensions, images, tags, meta_title, meta_description) VALUES
('Leica NA720 Automatic Level', 'leica-na720-automatic-level', 'Level optik otomatis Leica NA720 dengan akurasi 2.5mm/km dan magnification 20x. Dilengkapi dengan kompensator magnetik yang memberikan akurasi konsisten. Fokus minimum 0.6m dengan teropong berkualitas tinggi. Tahan debu dan air IP54. Cocok untuk survei konstruksi, leveling, dan aplikasi engineering yang membutuhkan akurasi tinggi.', 'Level optik otomatis dengan akurasi 2.5mm/km', 'LEI-NA720-LEVEL', 19900000.00, 21900000.00, 16000000.00, 5, 3, true, true, true, 15, 1.6, '{"panjang": "20 cm", "lebar": "20 cm", "tinggi": "14 cm"}', '["https://source.unsplash.com/400x300/?leica,level,automatic", "https://source.unsplash.com/400x300/?level,optical"]', '["level optik", "otomatis", "akurasi 2.5mm", "magnification 20x", "survei konstruksi", "leveling"]', 'Leica NA720 Automatic Level - Level Optik Otomatis dengan Akurasi 2.5mm/km', 'Jual Leica NA720 Automatic Level dengan akurasi 2.5mm/km dan magnification 20x. Kompensator magnetik, IP54, cocok untuk survei konstruksi.'),

('Topcon AT-B4 Automatic Level', 'topcon-at-b4-automatic-level', 'Level otomatis Topcon AT-B4 dengan akurasi 1.5mm/km dan magnification 24x. Dilengkapi dengan kompensator magnetik yang stabil dan reliable. Fokus minimum 0.3m dengan teropong berkualitas tinggi. Tahan debu dan air IP56. Cocok untuk survei konstruksi, monitoring, dan aplikasi engineering yang membutuhkan akurasi presisi.', 'Level otomatis dengan akurasi 1.5mm/km dan magnification 24x', 'TOP-ATB4-LEVEL', 17900000.00, 19900000.00, 14500000.00, 5, 4, true, false, true, 22, 1.8, '{"panjang": "22 cm", "lebar": "22 cm", "tinggi": "15 cm"}', '["https://source.unsplash.com/400x300/?topcon,level,automatic", "https://source.unsplash.com/400x300/?level,precision"]', '["level otomatis", "akurasi 1.5mm", "magnification 24x", "survei konstruksi", "monitoring", "engineering"]', 'Topcon AT-B4 Automatic Level - Level Otomatis dengan Akurasi 1.5mm/km', 'Beli Topcon AT-B4 Automatic Level dengan akurasi 1.5mm/km dan magnification 24x. Kompensator magnetik, IP56, cocok untuk survei konstruksi.'),

('Sokkia B40 Automatic Level', 'sokkia-b40-automatic-level', 'Level otomatis Sokkia B40 dengan akurasi 2.0mm/km dan magnification 24x. Dilengkapi dengan kompensator magnetik yang memberikan stabilitas tinggi. Fokus minimum 0.5m dengan teropong berkualitas. Tahan debu dan air IP54. Cocok untuk survei topografi, konstruksi, dan aplikasi leveling dengan akurasi standar.', 'Level otomatis dengan akurasi 2.0mm/km', 'SOK-B40-LEVEL', 13900000.00, 15900000.00, 11000000.00, 5, 5, true, true, true, 28, 1.4, '{"panjang": "19 cm", "lebar": "19 cm", "tinggi": "13 cm"}', '["https://source.unsplash.com/400x300/?sokkia,level,automatic", "https://source.unsplash.com/400x300/?level,construction"]', '["level otomatis", "akurasi 2.0mm", "magnification 24x", "survei topografi", "konstruksi", "leveling"]', 'Sokkia B40 Automatic Level - Level Otomatis dengan Akurasi 2.0mm/km', 'Jual Sokkia B40 Automatic Level dengan akurasi 2.0mm/km dan magnification 24x. Kompensator magnetik, IP54, cocok untuk survei topografi.'),

-- Laser Level Products  
('Leica Rugby 610 Laser Level', 'leica-rugby-610-laser-level', 'Laser level Leica Rugby 610 dengan teknologi dual-grade dan akurasi ±1.5mm/30m. Dilengkapi dengan self-leveling otomatis dan jangkauan hingga 600m dengan receiver. Laser merah dengan visibility tinggi. Tahan debu dan air IP67. Cocok untuk grading, excavation, dan aplikasi konstruksi outdoor yang membutuhkan akurasi tinggi.', 'Laser level dual-grade dengan akurasi ±1.5mm/30m', 'LEI-RUGBY610-LASER', 34900000.00, 37900000.00, 28000000.00, 6, 3, true, true, true, 12, 2.8, '{"panjang": "24 cm", "lebar": "24 cm", "tinggi": "21 cm"}', '["https://source.unsplash.com/400x300/?leica,rugby,laser", "https://source.unsplash.com/400x300/?laser,level,grading"]', '["laser level", "dual-grade", "akurasi 1.5mm", "self-leveling", "grading", "excavation", "konstruksi"]', 'Leica Rugby 610 Laser Level - Laser Level Dual-Grade dengan Akurasi ±1.5mm', 'Beli Leica Rugby 610 Laser Level dengan teknologi dual-grade dan akurasi ±1.5mm/30m. Self-leveling, jangkauan 600m, IP67, cocok untuk grading.'),

('Topcon RL-H5A Laser Level', 'topcon-rl-h5a-laser-level', 'Laser level Topcon RL-H5A dengan teknologi horizontal self-leveling dan akurasi ±10 arc second. Dilengkapi dengan dual-axis kompensator dan jangkauan hingga 800m dengan receiver. Laser merah dengan kecepatan rotasi variabel. Tahan debu dan air IP66. Cocok untuk leveling, grading, dan aplikasi konstruksi interior maupun eksterior.', 'Laser level horizontal dengan akurasi ±10 arc second', 'TOP-RLH5A-LASER', 24900000.00, 27900000.00, 20000000.00, 6, 4, true, false, true, 18, 2.2, '{"panjang": "22 cm", "lebar": "22 cm", "tinggi": "18 cm"}', '["https://source.unsplash.com/400x300/?topcon,laser,level", "https://source.unsplash.com/400x300/?laser,horizontal"]', '["laser level", "horizontal", "self-leveling", "akurasi 10 arc second", "leveling", "grading", "konstruksi"]', 'Topcon RL-H5A Laser Level - Laser Level Horizontal dengan Akurasi ±10 Arc Second', 'Jual Topcon RL-H5A Laser Level dengan teknologi horizontal self-leveling dan akurasi ±10 arc second. Jangkauan 800m, IP66, cocok untuk leveling.'),

('Spectra Precision GL722 Laser Level', 'spectra-precision-gl722-laser-level', 'Laser level Spectra Precision GL722 dengan teknologi dual-grade dan akurasi ±1.5mm/30m. Dilengkapi dengan self-leveling otomatis dan remote control. Jangkauan hingga 700m dengan receiver. Laser merah dengan visibility tinggi. Tahan debu dan air IP67. Cocok untuk grading, slope work, dan aplikasi konstruksi yang membutuhkan dual-grade capability.', 'Laser level dual-grade dengan remote control', 'SPEC-GL722-LASER', 29900000.00, 32900000.00, 24000000.00, 6, 8, true, true, true, 15, 2.5, '{"panjang": "23 cm", "lebar": "23 cm", "tinggi": "19 cm"}', '["https://source.unsplash.com/400x300/?spectra,laser,level", "https://source.unsplash.com/400x300/?laser,dual,grade"]', '["laser level", "dual-grade", "remote control", "akurasi 1.5mm", "grading", "slope work", "konstruksi"]', 'Spectra Precision GL722 Laser Level - Laser Level Dual-Grade dengan Remote Control', 'Beli Spectra Precision GL722 Laser Level dengan teknologi dual-grade dan remote control. Akurasi ±1.5mm/30m, jangkauan 700m, IP67.'),

-- Tripod Products
('Leica GST120-9 Carbon Tripod', 'leica-gst120-9-carbon-tripod', 'Tripod carbon fiber Leica GST120-9 dengan tinggi 1.02m - 1.65m dan beban maksimal 20kg. Dilengkapi dengan leg locking system yang cepat dan reliable. Konstruksi carbon fiber yang ringan namun kuat. Head attachment 5/8" x 11 thread. Cocok untuk GPS, total station, dan aplikasi surveying yang membutuhkan stabilitas tinggi.', 'Tripod carbon fiber dengan beban maksimal 20kg', 'LEI-GST120-9-TRIPOD', 8999000.00, 9999000.00, 7200000.00, 8, 3, true, true, true, 20, 2.8, '{"tinggi_min": "102 cm", "tinggi_max": "165 cm", "beban_max": "20 kg"}', '["https://source.unsplash.com/400x300/?tripod,carbon,fiber", "https://source.unsplash.com/400x300/?leica,tripod"]', '["tripod", "carbon fiber", "beban 20kg", "leg locking", "GPS", "total station", "surveying"]', 'Leica GST120-9 Carbon Tripod - Tripod Carbon Fiber untuk GPS dan Total Station', 'Beli Leica GST120-9 Carbon Tripod dengan konstruksi carbon fiber dan beban maksimal 20kg. Leg locking system cepat, cocok untuk GPS dan total station.'),

('Topcon Aluminum Tripod', 'topcon-aluminum-tripod', 'Tripod aluminum Topcon dengan tinggi 0.95m - 1.60m dan beban maksimal 15kg. Dilengkapi dengan leg locking system yang robust dan shoulder strap. Konstruksi aluminum yang tahan lama dan ekonomis. Head attachment 5/8" x 11 thread. Cocok untuk total station, theodolite, dan aplikasi surveying standar.', 'Tripod aluminum dengan beban maksimal 15kg', 'TOP-ALU-TRIPOD', 3999000.00, 4499000.00, 3200000.00, 8, 4, true, false, true, 35, 4.2, '{"tinggi_min": "95 cm", "tinggi_max": "160 cm", "beban_max": "15 kg"}', '["https://source.unsplash.com/400x300/?tripod,aluminum", "https://source.unsplash.com/400x300/?topcon,tripod"]', '["tripod", "aluminum", "beban 15kg", "robust", "total station", "theodolite", "surveying"]', 'Topcon Aluminum Tripod - Tripod Aluminum untuk Total Station dan Theodolite', 'Jual Topcon Aluminum Tripod dengan beban maksimal 15kg dan konstruksi tahan lama. Leg locking robust, cocok untuk total station dan theodolite.'),

('Sokkia Wooden Tripod', 'sokkia-wooden-tripod', 'Tripod kayu Sokkia dengan tinggi 1.00m - 1.70m dan beban maksimal 25kg. Dilengkapi dengan leg locking system tradisional yang reliable. Konstruksi kayu berkualitas tinggi yang stabil dan tahan lama. Head attachment 5/8" x 11 thread. Cocok untuk instrumen survei berat dan aplikasi yang membutuhkan stabilitas maksimal.', 'Tripod kayu dengan beban maksimal 25kg', 'SOK-WOOD-TRIPOD', 2999000.00, 3499000.00, 2400000.00, 8, 5, true, true, true, 25, 6.5, '{"tinggi_min": "100 cm", "tinggi_max": "170 cm", "beban_max": "25 kg"}', '["https://source.unsplash.com/400x300/?tripod,wooden", "https://source.unsplash.com/400x300/?sokkia,tripod"]', '["tripod", "kayu", "beban 25kg", "stabilitas maksimal", "instrumen berat", "survei"]', 'Sokkia Wooden Tripod - Tripod Kayu dengan Stabilitas Maksimal | Beban 25kg', 'Beli Sokkia Wooden Tripod dengan konstruksi kayu berkualitas tinggi dan beban maksimal 25kg. Stabilitas maksimal untuk instrumen survei berat.'),

-- GPS Accessories
('Garmin Carrying Case', 'garmin-carrying-case', 'Carrying case Garmin untuk GPS handheld dengan konstruksi nylon yang tahan lama. Dilengkapi dengan belt clip dan lanyard. Kompartemen tambahan untuk aksesori kecil. Tahan air dengan zipper waterproof. Cocok untuk melindungi GPS handheld dari benturan dan cuaca buruk.', 'Carrying case nylon untuk GPS handheld', 'GAR-CASE-001', 399000.00, 499000.00, 280000.00, 9, 1, true, false, true, 50, 0.2, '{"panjang": "12 cm", "lebar": "8 cm", "tinggi": "4 cm"}', '["https://source.unsplash.com/400x300/?garmin,case,carrying", "https://source.unsplash.com/400x300/?gps,case"]', '["carrying case", "nylon", "belt clip", "lanyard", "waterproof", "GPS handheld"]', 'Garmin Carrying Case - Carrying Case Nylon untuk GPS Handheld | Tahan Air', 'Beli Garmin Carrying Case dengan konstruksi nylon tahan lama dan zipper waterproof. Belt clip, lanyard, cocok untuk melindungi GPS handheld.'),

('Trimble External Antenna', 'trimble-external-antenna', 'Antena eksternal Trimble dengan teknologi multi-frequency dan gain tinggi. Kabel 5m dengan konektor TNC. Dilengkapi dengan magnetic mount dan ground plane. Cocok untuk meningkatkan signal reception pada GNSS receiver di area dengan signal lemah atau obstructed sky view.', 'Antena eksternal multi-frequency dengan gain tinggi', 'TRI-ANT-EXT', 4999000.00, 5499000.00, 4000000.00, 9, 2, true, true, true, 20, 1.5, '{"kabel": "5 m", "konektor": "TNC", "mount": "Magnetic"}', '["https://source.unsplash.com/400x300/?antenna,external", "https://source.unsplash.com/400x300/?trimble,antenna"]', '["antena eksternal", "multi-frequency", "gain tinggi", "magnetic mount", "GNSS receiver", "signal reception"]', 'Trimble External Antenna - Antena Eksternal Multi-Frequency untuk GNSS', 'Beli Trimble External Antenna dengan teknologi multi-frequency dan gain tinggi. Kabel 5m, magnetic mount, cocok untuk meningkatkan signal reception.'),

('Leica Battery Charger', 'leica-battery-charger', 'Battery charger Leica dengan teknologi intelligent charging dan LED indicator. Kompatibel dengan berbagai tipe baterai Leica. Input 100-240V AC dengan output 12V DC. Dilengkapi dengan car adapter dan wall adapter. Cocok untuk charging baterai instrumen survei Leica di lapangan maupun di kantor.', 'Battery charger dengan intelligent charging', 'LEI-CHARGER-001', 1999000.00, 2299000.00, 1500000.00, 9, 3, true, false, true, 30, 0.8, '{"input": "100-240V AC", "output": "12V DC", "adapter": "Car + Wall"}', '["https://source.unsplash.com/400x300/?battery,charger", "https://source.unsplash.com/400x300/?leica,charger"]', '["battery charger", "intelligent charging", "LED indicator", "car adapter", "wall adapter", "instrumen survei"]', 'Leica Battery Charger - Battery Charger dengan Intelligent Charging', 'Beli Leica Battery Charger dengan teknologi intelligent charging dan LED indicator. Car adapter, wall adapter, cocok untuk instrumen survei Leica.'),

-- Software Survey
('Leica Captivate Software', 'leica-captivate-software', 'Software survei Leica Captivate dengan antarmuka 3D dan workflow yang intuitif. Dilengkapi dengan fitur CAD, stakeout, dan data management. Kompatibel dengan semua instrumen Leica. Fitur cloud connectivity untuk sinkronisasi data real-time. Cocok untuk survei konstruksi, engineering, dan aplikasi profesional yang membutuhkan efficiency dan accuracy.', 'Software survei 3D dengan workflow intuitif', 'LEI-CAPTIVATE-SW', 15999000.00, 17999000.00, 12000000.00, 10, 3, true, true, true, 100, 0.1, '{"format": "Digital Download", "platform": "Windows/Android"}', '["https://source.unsplash.com/400x300/?software,survey", "https://source.unsplash.com/400x300/?leica,captivate"]', '["software survei", "3D", "workflow intuitif", "CAD", "stakeout", "cloud connectivity", "survei konstruksi"]', 'Leica Captivate Software - Software Survei 3D dengan Workflow Intuitif', 'Beli Leica Captivate Software dengan antarmuka 3D dan workflow intuitif. Fitur CAD, stakeout, cloud connectivity, cocok untuk survei konstruksi.'),

('Topcon MAGNET Field Software', 'topcon-magnet-field-software', 'Software survei Topcon MAGNET Field dengan kemampuan data collection dan stakeout yang komprehensif. Dilengkapi dengan fitur CAD, mapping, dan road design. Kompatibel dengan semua instrumen Topcon. Interface yang user-friendly dengan customizable workflow. Cocok untuk survei konstruksi, cadastral, dan aplikasi engineering yang membutuhkan flexibility dan precision.', 'Software survei dengan data collection dan stakeout komprehensif', 'TOP-MAGNET-SW', 12999000.00, 14999000.00, 10000000.00, 10, 4, true, false, true, 100, 0.1, '{"format": "Digital Download", "platform": "Windows/Android"}', '["https://source.unsplash.com/400x300/?topcon,magnet,software", "https://source.unsplash.com/400x300/?survey,software"]', '["software survei", "data collection", "stakeout", "CAD", "mapping", "road design", "survei konstruksi"]', 'Topcon MAGNET Field Software - Software Survei dengan Data Collection Komprehensif', 'Beli Topcon MAGNET Field Software dengan kemampuan data collection dan stakeout. Fitur CAD, mapping, road design, cocok untuk survei konstruksi.');

-- Add featured products
UPDATE products SET is_featured = true WHERE id IN (22, 25, 26, 28, 32, 35);

-- Check current count
SELECT COUNT(*) as total_products FROM products;
