-- Additional GPS Products to reach 100+ items
-- Insert more products across all categories

INSERT INTO products (
    name, slug, description, short_description, sku, price, compare_price, cost_price,
    category_id, brand_id, is_active, is_featured, in_stock, stock_quantity, weight,
    dimensions, images, tags, meta_title, meta_description
) VALUES

-- More GPS Handheld Products
('Garmin eTrex 22x', 'garmin-etrex-22x', 
'GPS handheld Garmin eTrex 22x dengan peta TopoActive preloaded dan layar TFT 2.2". Dilengkapi dengan kompas 3-axis dan barometer. Mendukung GPS dan GLONASS untuk akurasi yang lebih baik. Tahan air IPX7 dengan baterai AA hingga 25 jam. Cocok untuk hiking, geocaching, dan aktivitas outdoor dengan budget terbatas.', 
'GPS handheld dengan peta TopoActive dan sensor lengkap', 
'GAR-ETREX-22X', 2799000.00, 2999000.00, 2200000.00, 
1, 1, true, false, true, 40, 0.14, 
'{"panjang": "5.4 cm", "lebar": "10.3 cm", "tinggi": "3.3 cm"}', 
'["https://source.unsplash.com/400x300/?garmin,etrex,22x", "https://source.unsplash.com/400x300/?gps,budget"]', 
'["GPS handheld", "TopoActive", "kompas", "barometer", "hiking", "geocaching", "budget"]', 
'Garmin eTrex 22x - GPS Handheld dengan Peta TopoActive | Harga Terjangkau', 
'Beli Garmin eTrex 22x GPS handheld dengan peta TopoActive preloaded dan sensor lengkap. Kompas 3-axis, barometer, IPX7, harga terjangkau.'),

('Garmin eTrex 10', 'garmin-etrex-10', 
'GPS handheld Garmin eTrex 10 dengan desain yang simple dan mudah digunakan. Layar monokrom 2.2" dengan resolusi 128x160 piksel. Mendukung GPS dan GLONASS dengan akurasi 3 meter. Tahan air IPX7 dengan baterai AA hingga 25 jam. Cocok untuk hiking basic, geocaching, dan aktivitas outdoor entry-level.', 
'GPS handheld entry-level dengan desain simple', 
'GAR-ETREX-10', 1899000.00, 2199000.00, 1500000.00, 
1, 1, true, false, true, 60, 0.14, 
'{"panjang": "5.4 cm", "lebar": "10.3 cm", "tinggi": "3.3 cm"}', 
'["https://source.unsplash.com/400x300/?garmin,etrex,10", "https://source.unsplash.com/400x300/?gps,entry"]', 
'["GPS handheld", "entry-level", "simple", "monokrom", "hiking", "geocaching", "basic"]', 
'Garmin eTrex 10 - GPS Handheld Entry-Level dengan Desain Simple', 
'Beli Garmin eTrex 10 GPS handheld entry-level dengan desain simple dan mudah digunakan. Layar monokrom, IPX7, cocok untuk hiking basic.'),

('Garmin Oregon 700', 'garmin-oregon-700', 
'GPS handheld Garmin Oregon 700 dengan layar touchscreen 3" dan dual battery system. Dilengkapi dengan kompas 3-axis, barometer, dan altimeter. Mendukung GPS, GLONASS, dan Galileo. Tahan air IPX7 dengan baterai AA atau Li-ion. Cocok untuk hiking, hunting, dan aktivitas outdoor yang membutuhkan navigasi presisi.', 
'GPS handheld dengan touchscreen dan dual battery', 
'GAR-OREGON-700', 6999000.00, 7999000.00, 5500000.00, 
1, 1, true, false, true, 30, 0.21, 
'{"panjang": "6.1 cm", "lebar": "11.4 cm", "tinggi": "3.3 cm"}', 
'["https://source.unsplash.com/400x300/?garmin,oregon,700", "https://source.unsplash.com/400x300/?gps,hunting"]', 
'["GPS handheld", "touchscreen", "dual battery", "kompas", "barometer", "hiking", "hunting"]', 
'Garmin Oregon 700 - GPS Handheld dengan Touchscreen dan Dual Battery', 
'Beli Garmin Oregon 700 GPS handheld dengan layar touchscreen 3" dan dual battery system. Kompas, barometer, altimeter, cocok untuk hiking dan hunting.'),

('Magellan eXplorist 310', 'magellan-explorist-310', 
'GPS handheld Magellan eXplorist 310 dengan layar monokrom 2.2" dan design yang robust. Dilengkapi dengan electronic compass dan barometric altimeter. Mendukung GPS dan GLONASS. Tahan air IPX7 dengan baterai AA hingga 18 jam. Cocok untuk outdoor adventure, geocaching, dan aktivitas basic navigation.', 
'GPS handheld dengan electronic compass dan barometer', 
'MAG-EXPL-310', 2199000.00, 2499000.00, 1700000.00, 
1, 6, true, false, true, 45, 0.22, 
'{"panjang": "6.1 cm", "lebar": "11.4 cm", "tinggi": "3.0 cm"}', 
'["https://source.unsplash.com/400x300/?magellan,explorist,310", "https://source.unsplash.com/400x300/?gps,robust"]', 
'["GPS handheld", "monokrom", "electronic compass", "barometer", "outdoor adventure", "geocaching", "basic navigation"]', 
'Magellan eXplorist 310 - GPS Handheld dengan Electronic Compass dan Barometer', 
'Beli Magellan eXplorist 310 GPS handheld dengan layar monokrom dan design robust. Electronic compass, barometer, IPX7, cocok untuk outdoor adventure.'),

-- More GPS Surveying Products
('Leica GS18 I GNSS', 'leica-gs18-i-gnss', 
'GNSS receiver Leica GS18 I dengan teknologi RTK tilt compensation dan visual positioning. Dilengkapi dengan IMU dan kamera untuk pengukuran yang lebih mudah dan akurat. Mendukung semua konstelasi satelit dengan akurasi horizontal 5mm + 0.5ppm. Fitur tilt compensation memungkinkan pengukuran tanpa perlu menegakkan pole. Cocok untuk survei topografi, konstruksi, dan aplikasi GIS.', 
'GNSS receiver dengan tilt compensation dan visual positioning', 
'LEI-GS18-I', 179900000.00, 189900000.00, 155000000.00, 
2, 3, true, true, true, 6, 1.4, 
'{"diameter": "20.2 cm", "tinggi": "16.3 cm"}', 
'["https://source.unsplash.com/400x300/?leica,gs18,gnss", "https://source.unsplash.com/400x300/?gnss,tilt"]', 
'["GNSS receiver", "tilt compensation", "visual positioning", "RTK", "survei topografi", "konstruksi", "GIS"]', 
'Leica GS18 I GNSS - GNSS Receiver dengan Tilt Compensation | Jual Leica', 
'Jual Leica GS18 I GNSS receiver dengan teknologi tilt compensation dan visual positioning. Akurasi 5mm, pengukuran tanpa perlu menegakkan pole.'),

('Topcon HiPer VR GNSS', 'topcon-hiper-vr-gnss', 
'GNSS receiver Topcon HiPer VR dengan teknologi Fence Antenna dan Universal Tracking Channels. Mendukung semua konstelasi satelit dengan 226 channels. Akurasi horizontal 3mm + 0.5ppm dan vertikal 5mm + 0.5ppm. Dilengkapi dengan Bluetooth dan WiFi untuk konektivitas yang fleksibel. Baterai internal hingga 5.5 jam operasi. Cocok untuk survei kadaster, konstruksi, dan monitoring deformasi.', 
'GNSS receiver dengan Fence Antenna dan Universal Tracking', 
'TOP-HIPER-VR', 159900000.00, 169900000.00, 135000000.00, 
2, 4, true, false, true, 12, 1.1, 
'{"diameter": "18.6 cm", "tinggi": "11.2 cm"}', 
'["https://source.unsplash.com/400x300/?topcon,hiper,gnss", "https://source.unsplash.com/400x300/?gnss,fence"]', 
'["GNSS receiver", "Fence Antenna", "Universal Tracking", "226 channels", "survei kadaster", "konstruksi", "monitoring"]', 
'Topcon HiPer VR GNSS - GNSS Receiver dengan Fence Antenna Technology', 
'Beli Topcon HiPer VR GNSS receiver dengan teknologi Fence Antenna dan 226 channels. Akurasi 3mm, Bluetooth, WiFi. Cocok untuk survei profesional.'),

('CHC X91+ GNSS Receiver', 'chc-x91-gnss-receiver', 
'GNSS receiver CHC X91+ dengan teknologi multi-constellation dan akurasi sub-centimeter. Mendukung GPS, GLONASS, Galileo, dan BeiDou. Dilengkapi dengan integrated radio dan Bluetooth connectivity. Baterai internal hingga 8 jam operasi. Cocok untuk survei kadaster, konstruksi, dan aplikasi mapping dengan harga kompetitif.', 
'GNSS receiver multi-constellation dengan akurasi sub-centimeter', 
'CHC-X91-GNSS', 119900000.00, 129900000.00, 95000000.00, 
2, 10, true, true, true, 10, 1.3, 
'{"diameter": "19.5 cm", "tinggi": "12.8 cm"}', 
'["https://source.unsplash.com/400x300/?chc,x91,gnss", "https://source.unsplash.com/400x300/?gnss,multi"]', 
'["GNSS receiver", "multi-constellation", "sub-centimeter", "integrated radio", "survei kadaster", "konstruksi", "mapping"]', 
'CHC X91+ GNSS Receiver - GNSS Receiver Multi-Constellation dengan Akurasi Sub-Centimeter', 
'Beli CHC X91+ GNSS Receiver dengan teknologi multi-constellation dan akurasi sub-centimeter. Integrated radio, Bluetooth, harga kompetitif untuk survei kadaster.'),

-- More Total Station Products
('Topcon GT-1200 Robotic', 'topcon-gt-1200-robotic', 
'Total station robotik Topcon GT-1200 dengan teknologi Autolock dan akurasi angular 1". Dilengkapi dengan sistem servo motor untuk tracking otomatis. Jangkauan EDM hingga 3000m dengan prisma dan 800m tanpa prisma. Layar LCD dual-face dengan backlight. Kompensator dual-axis untuk akurasi yang konsisten. Cocok untuk survei konstruksi, monitoring struktur, dan aplikasi engineering yang membutuhkan efisiensi tinggi.', 
'Total station robotik dengan teknologi Autolock dan tracking otomatis', 
'TOP-GT1200-ROB', 289900000.00, 309900000.00, 245000000.00, 
3, 4, true, true, true, 8, 6.2, 
'{"panjang": "38 cm", "lebar": "22 cm", "tinggi": "18 cm"}', 
'["https://source.unsplash.com/400x300/?topcon,gt1200,robotic", "https://source.unsplash.com/400x300/?total,station,robotic"]', 
'["total station robotik", "Autolock", "tracking otomatis", "survei konstruksi", "monitoring struktur", "engineering"]', 
'Topcon GT-1200 Robotic - Total Station Robotik dengan Autolock | Harga Terbaik', 
'Jual Topcon GT-1200 Robotic Total Station dengan teknologi Autolock dan tracking otomatis. Akurasi 1", jangkauan 3000m, cocok untuk survei konstruksi.'),

('HI-TARGET ZTS-360R Total Station', 'hi-target-zts-360r-total-station', 
'Total station HI-TARGET ZTS-360R dengan akurasi angular 2" dan teknologi reflectorless EDM. Jangkauan pengukuran hingga 3000m dengan prisma dan 600m tanpa prisma. Dilengkapi dengan layar LCD dual-face dan illuminated keypad. Kompensator dual-axis dengan sensitivitas 3". Baterai Li-ion dengan daya tahan hingga 20 jam. Cocok untuk survei konstruksi, monitoring, dan aplikasi engineering dengan harga kompetitif.', 
'Total station dengan akurasi 2" dan reflectorless EDM', 
'HIT-ZTS360R-TS', 129900000.00, 139900000.00, 105000000.00, 
3, 10, true, true, true, 12, 5.2, 
'{"panjang": "34 cm", "lebar": "19 cm", "tinggi": "17 cm"}', 
'["https://source.unsplash.com/400x300/?hi-target,zts360r", "https://source.unsplash.com/400x300/?total,station,reflectorless"]', 
'["total station", "akurasi 2 detik", "reflectorless EDM", "survei konstruksi", "monitoring", "engineering"]', 
'HI-TARGET ZTS-360R Total Station - Total Station dengan Akurasi 2" | Harga Kompetitif', 
'Jual HI-TARGET ZTS-360R Total Station dengan akurasi angular 2" dan reflectorless EDM. Jangkauan 3000m, baterai 20 jam, harga kompetitif.'),

-- Theodolite Products
('Leica TM50 Theodolite', 'leica-tm50-theodolite', 
'Theodolite monitoring Leica TM50 dengan akurasi angular 0.5" dan teknologi Automatic Target Recognition (ATR). Dilengkapi dengan sistem servo motor untuk tracking otomatis dan kompensator dual-axis. Jangkauan pengukuran hingga 3000m dengan target khusus. Layar touchscreen 5" dengan antarmuka intuitif. Tahan debu dan air IP65. Cocok untuk monitoring deformasi, survei geodetik, dan aplikasi engineering presisi tinggi.', 
'Theodolite monitoring dengan akurasi 0.5" dan ATR', 
'LEI-TM50-THEO', 459900000.00, 479900000.00, 385000000.00, 
4, 3, true, true, true, 3, 6.8, 
'{"panjang": "36 cm", "lebar": "21 cm", "tinggi": "19 cm"}', 
'["https://source.unsplash.com/400x300/?leica,tm50,theodolite", "https://source.unsplash.com/400x300/?theodolite,monitoring"]', 
'["theodolite monitoring", "akurasi 0.5 detik", "ATR", "tracking otomatis", "monitoring deformasi", "survei geodetik"]', 
'Leica TM50 Theodolite - Theodolite Monitoring dengan Akurasi 0.5" | Jual Leica', 
'Beli Leica TM50 Theodolite monitoring dengan akurasi angular 0.5" dan ATR. Tracking otomatis, IP65, cocok untuk monitoring deformasi dan survei geodetik.'),

('Topcon DT-209 Theodolite', 'topcon-dt-209-theodolite', 
'Theodolite optik Topcon DT-209 dengan akurasi angular 9" dan teknologi Absolute Encoding. Dilengkapi dengan teropong 30x magnification dan resolusi display 1". Kompensator dual-axis dengan sensitivitas 3" per 2mm. Baterai AA dengan daya tahan hingga 100 jam. Tahan debu dan air IP54. Cocok untuk survei topografi, konstruksi, dan aplikasi engineering dengan akurasi standar.', 
'Theodolite optik dengan akurasi 9" dan Absolute Encoding', 
'TOP-DT209-THEO', 24900000.00, 27900000.00, 20000000.00, 
4, 4, true, false, true, 25, 3.8, 
'{"panjang": "30 cm", "lebar": "16 cm", "tinggi": "15 cm"}', 
'["https://source.unsplash.com/400x300/?topcon,dt209,theodolite", "https://source.unsplash.com/400x300/?theodolite,optical"]', 
'["theodolite optik", "akurasi 9 detik", "Absolute Encoding", "30x magnification", "survei topografi", "konstruksi"]', 
'Topcon DT-209 Theodolite - Theodolite Optik dengan Akurasi 9" | Harga Terbaik', 
'Jual Topcon DT-209 Theodolite optik dengan akurasi angular 9" dan Absolute Encoding. Magnification 30x, baterai 100 jam, cocok untuk survei topografi.');

-- Continue with more categories and reach 100+ products
-- This script will be executed in parts to avoid timeout
