-- Enhanced seed data with 30+ GPS products across multiple categories and brands
-- Clear existing data first
TRUNCATE TABLE products, categories, brands, blog_posts RESTART IDENTITY CASCADE;

-- Insert Categories with SEO slugs
INSERT INTO categories (name, slug, description, is_active, sort_order) VALUES
('GNSS Receivers', 'gnss-receivers-professional-surveying', 'High-precision GNSS receivers for professional surveying and mapping applications', true, 1),
('Total Stations', 'total-stations-precision-measurement', 'Electronic total stations for accurate distance and angle measurements', true, 2),
('Theodolites', 'theodolites-angle-measurement', 'Precision theodolites for angular measurements in surveying and construction', true, 3),
('Laser Levels', 'laser-levels-construction-grade', 'Professional laser levels for construction and surveying applications', true, 4),
('GPS Handheld Devices', 'gps-handheld-navigation-devices', 'Portable GPS devices for field navigation and data collection', true, 5),
('Drone Surveying Equipment', 'drone-surveying-mapping-equipment', 'UAV systems and accessories for aerial surveying and mapping', true, 6),
('Survey Software', 'survey-software-data-processing', 'Professional software solutions for survey data processing and CAD', true, 7),
('Measuring Tapes & Tools', 'measuring-tapes-surveying-tools', 'Traditional measuring instruments and surveying accessories', true, 8),
('Safety Equipment', 'safety-equipment-field-surveying', 'Safety gear and protective equipment for field surveying work', true, 9),
('Tripods & Accessories', 'tripods-survey-accessories', 'Professional tripods, prisms, and surveying accessories', true, 10);

-- Insert Brands with SEO slugs  
INSERT INTO brands (name, slug, description, is_active) VALUES
('Trimble', 'trimble-precision-positioning-technology', 'Leading provider of advanced positioning solutions and geospatial technology', true),
('Leica Geosystems', 'leica-geosystems-measurement-solutions', 'Premium measurement and surveying solutions for professionals worldwide', true),
('Topcon', 'topcon-positioning-systems-technology', 'Innovative positioning technology and solutions for construction and surveying', true),
('Sokkia', 'sokkia-professional-surveying-equipment', 'Professional surveying instruments and measurement solutions', true),
('Spectra Precision', 'spectra-precision-construction-lasers', 'Construction and surveying laser systems and positioning technology', true),
('Garmin', 'garmin-gps-navigation-technology', 'Leading GPS technology and navigation solutions for professionals', true),
('DJI', 'dji-drone-aerial-imaging-systems', 'Professional drone systems for aerial surveying and mapping applications', true),
('Nikon', 'nikon-surveying-optical-instruments', 'Precision optical instruments and surveying equipment', true),
('Pentax', 'pentax-precision-surveying-instruments', 'High-quality surveying instruments and measurement solutions', true),
('South Surveying', 'south-surveying-gnss-solutions', 'Professional GNSS and surveying solutions for global markets', true),
('CHC Navigation', 'chc-navigation-precision-positioning', 'Advanced GNSS and positioning technology solutions', true),
('Carlson Software', 'carlson-software-survey-solutions', 'Professional surveying and civil engineering software solutions', true);

-- Insert 30+ Products with detailed specifications
INSERT INTO products (name, slug, description, specifications, sku, price, compare_price, category_id, brand_id, is_active, is_featured, in_stock, stock_quantity, images, tags, meta_title, meta_description) VALUES

-- GNSS Receivers (Category 1)
('Trimble R12i GNSS Receiver', 'trimble-r12i-gnss-receiver-professional-surveying', 'Professional GNSS receiver with integrated IMU technology for high-precision surveying and mapping applications. Features advanced tilt compensation and multi-constellation tracking.', '<h3>Technical Specifications</h3><ul><li>Channels: 440+ channels tracking all GNSS constellations</li><li>Accuracy: Horizontal 3mm + 0.1ppm, Vertical 3.5mm + 0.4ppm</li><li>Tilt Compensation: Up to 30° with IMU technology</li><li>Operating Temperature: -40°C to +65°C</li><li>Battery Life: 35+ hours continuous operation</li><li>Communication: Wi-Fi, Bluetooth, cellular modem</li></ul>', 'TRM-R12I-001', 15999.00, 17999.00, 1, 1, true, true, true, 5, '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400", "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400"]', '["gnss", "surveying", "trimble", "precision", "gps"]', 'Trimble R12i GNSS Receiver - Professional Surveying Equipment', 'High-precision GNSS receiver with IMU technology for professional surveying. 3mm accuracy with tilt compensation up to 30 degrees.'),

('Leica GS18 T GNSS RTK Rover', 'leica-gs18-t-gnss-rtk-rover-tilt-compensation', 'Revolutionary GNSS RTK rover with visual positioning technology and tilt compensation. Perfect for challenging surveying environments with superior accuracy.', '<h3>Technical Specifications</h3><ul><li>Tilt Range: 0° to 60° with full accuracy</li><li>Accuracy: 1cm + 1ppm horizontal</li><li>Visual Positioning: Integrated camera for point verification</li><li>Constellations: GPS, GLONASS, Galileo, BeiDou, QZSS</li><li>Battery: 7+ hours typical operation</li><li>Connectivity: Bluetooth, Wi-Fi, GSM/LTE</li></ul>', 'LCA-GS18T-001', 18999.00, 21999.00, 1, 2, true, true, true, 3, '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400"]', '["leica", "gnss", "rtk", "tilt", "visual-positioning"]', 'Leica GS18 T GNSS RTK Rover - Tilt Compensation Technology', 'Revolutionary GNSS rover with 60° tilt compensation and visual positioning technology for superior surveying accuracy.'),

('Topcon HiPer VR GNSS Receiver', 'topcon-hiper-vr-gnss-receiver-virtual-reference', 'Advanced GNSS receiver with Virtual Reference Station technology. Ideal for high-productivity surveying with network RTK capabilities.', '<h3>Technical Specifications</h3><ul><li>Accuracy: 3mm + 0.1ppm horizontal RTK</li><li>Channels: 226 channels all-in-view tracking</li><li>Update Rate: Up to 20Hz positioning</li><li>Cold Start: <60 seconds</li><li>Operating Range: -40°C to +65°C</li><li>Communication: Integrated cellular, Wi-Fi, Bluetooth</li></ul>', 'TPC-HIPERVR-001', 12999.00, 14999.00, 1, 3, true, false, true, 8, '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400"]', '["topcon", "gnss", "vrs", "network-rtk"]', 'Topcon HiPer VR GNSS Receiver - Virtual Reference Technology', 'Advanced GNSS receiver with VRS technology for high-productivity surveying and network RTK applications.'),

('Sokkia GRX3 GNSS Receiver', 'sokkia-grx3-gnss-receiver-multi-constellation', 'Reliable GNSS receiver with multi-constellation tracking and exceptional signal processing. Built for demanding surveying applications.', '<h3>Technical Specifications</h3><ul><li>Constellations: GPS, GLONASS, Galileo, BeiDou</li><li>Accuracy: 3mm + 0.5ppm horizontal</li><li>Channels: 184 channels</li><li>Battery: 8+ hours continuous</li><li>Environmental: IP67 rating</li><li>Data Logging: Internal 8GB memory</li></ul>', 'SOK-GRX3-001', 9999.00, 11999.00, 1, 4, true, false, true, 12, '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400"]', '["sokkia", "gnss", "multi-constellation", "reliable"]', 'Sokkia GRX3 GNSS Receiver - Multi-Constellation Tracking', 'Reliable GNSS receiver with multi-constellation tracking for demanding surveying applications. 3mm precision accuracy.'),

-- Total Stations (Category 2)
('Leica TS16 Total Station', 'leica-ts16-total-station-robotic-atr-plus', 'Premium robotic total station with ATR PLUS technology and PowerSearch. Revolutionary measurement technology for maximum productivity.', '<h3>Technical Specifications</h3><ul><li>Angle Accuracy: 1" (0.3mgon)</li><li>Distance Accuracy: 1mm + 1.5ppm</li><li>Range: 1000m to single prism</li><li>PowerSearch: 360° prism search in 7 seconds</li><li>Operating Time: 26 hours dual battery</li><li>Display: 5" high-resolution touchscreen</li></ul>', 'LCA-TS16-001', 28999.00, 32999.00, 2, 2, true, true, true, 2, '["https://images.unsplash.com/photo-1581094289206-c0ddd9e21b0e?w=400"]', '["leica", "total-station", "robotic", "atr-plus"]', 'Leica TS16 Total Station - Robotic ATR PLUS Technology', 'Premium robotic total station with ATR PLUS and PowerSearch technology for maximum surveying productivity.'),

('Topcon GT-1200 Robotic Total Station', 'topcon-gt-1200-robotic-total-station-ultrasonic', 'Advanced robotic total station with ultrasonic communication and automatic tracking. Perfect for one-person surveying operations.', '<h3>Technical Specifications</h3><ul><li>Angle Measurement: 1" accuracy</li><li>Distance Range: 4000m reflectorless</li><li>Tracking Range: 300m to single prism</li><li>Communication: Ultrasonic and radio</li><li>Display: Large backlit LCD</li><li>Environmental: -20°C to +50°C</li></ul>', 'TPC-GT1200-001', 32999.00, 35999.00, 2, 3, true, true, true, 1, '["https://images.unsplash.com/photo-1581094289206-c0ddd9e21b0e?w=400"]', '["topcon", "robotic", "total-station", "ultrasonic"]', 'Topcon GT-1200 Robotic Total Station - Ultrasonic Communication', 'Advanced robotic total station with ultrasonic communication for efficient one-person surveying operations.'),

('Trimble S9 Total Station', 'trimble-s9-total-station-hp-edr-technology', 'High-precision total station with HP EDM technology and MagDrive servo motors. Exceptional accuracy for demanding measurements.', '<h3>Technical Specifications</h3><ul><li>Angular Accuracy: 1" (0.3mgon)</li><li>Distance Accuracy: 1mm + 1ppm</li><li>HP EDM Range: 5500m to single prism</li><li>MagDrive Technology: Maintenance-free servo motors</li><li>Display: Full-color touchscreen</li><li>Autolock: Fast and reliable target acquisition</li></ul>', 'TRM-S9-001', 25999.00, 28999.00, 2, 1, true, false, true, 4, '["https://images.unsplash.com/photo-1581094289206-c0ddd9e21b0e?w=400"]', '["trimble", "total-station", "hp-edr", "magdrive"]', 'Trimble S9 Total Station - HP EDR Technology', 'High-precision total station with HP EDM technology and MagDrive servo motors for exceptional accuracy.'),

('Sokkia iX-1003 Robotic Total Station', 'sokkia-ix-1003-robotic-total-station-hybrid', 'Innovative hybrid positioning system combining total station and GNSS technology. Ultimate flexibility for any surveying project.', '<h3>Technical Specifications</h3><ul><li>Angle Accuracy: 3" standard</li><li>EDM Range: 2000m reflectorless</li><li>GNSS Integration: Built-in GPS receiver</li><li>Hybrid Positioning: Seamless TS-GNSS switching</li><li>Display: Large color touchscreen</li><li>Communication: Bluetooth, Wi-Fi</li></ul>', 'SOK-IX1003-001', 19999.00, 22999.00, 2, 4, true, false, true, 6, '["https://images.unsplash.com/photo-1581094289206-c0ddd9e21b0e?w=400"]', '["sokkia", "robotic", "hybrid", "gnss-integration"]', 'Sokkia iX-1003 Robotic Total Station - Hybrid Positioning', 'Innovative hybrid positioning system combining total station and GNSS technology for ultimate surveying flexibility.'),

-- Theodolites (Category 3)
('Pentax ETH-520 Electronic Theodolite', 'pentax-eth-520-electronic-theodolite-precision', 'Precision electronic theodolite with dual-axis compensation and superior optics. Ideal for construction and surveying applications.', '<h3>Technical Specifications</h3><ul><li>Angle Accuracy: 20" (6mgon)</li><li>Magnification: 30x telescope</li><li>Dual-axis Compensation: Automatic tilt correction</li><li>Display: Large dual-sided LCD</li><li>Battery: NiMH rechargeable, 24 hours</li><li>Environmental: IP54 dust and water protection</li></ul>', 'PNX-ETH520-001', 3999.00, 4499.00, 3, 9, true, false, true, 15, '["https://images.unsplash.com/photo-1621261361075-816a81202d41?w=400"]', '["pentax", "theodolite", "electronic", "precision"]', 'Pentax ETH-520 Electronic Theodolite - Precision Measurement', 'Precision electronic theodolite with dual-axis compensation for construction and surveying applications.'),

('Nikon NE-20SC Theodolite', 'nikon-ne-20sc-theodolite-superior-optics', 'Professional theodolite with superior Nikon optics and rugged construction. Reliable performance in harsh field conditions.', '<h3>Technical Specifications</h3><ul><li>Reading Accuracy: 20" (6mgon)</li><li>Telescope: 30x magnification</li><li>Minimum Focus: 1.3m</li><li>Compensator: Single-axis liquid</li><li>Display: Easy-read LCD both sides</li><li>Construction: Aluminum die-cast housing</li></ul>', 'NKN-NE20SC-001', 2999.00, 3499.00, 3, 8, true, false, true, 20, '["https://images.unsplash.com/photo-1621261361075-816a81202d41?w=400"]', '["nikon", "theodolite", "optics", "rugged"]', 'Nikon NE-20SC Theodolite - Superior Optics', 'Professional theodolite with superior Nikon optics and rugged construction for reliable field performance.'),

-- Laser Levels (Category 4)
('Spectra Precision GL722 Dual Grade Laser', 'spectra-precision-gl722-dual-grade-laser-level', 'Professional dual grade laser for construction applications. Automatic leveling with exceptional accuracy and range.', '<h3>Technical Specifications</h3><ul><li>Accuracy: ±1.5mm at 30m</li><li>Working Range: 600m diameter</li><li>Grade Range: -10% to +25%</li><li>Self-Leveling: ±6° range</li><li>Operating Time: 60+ hours</li><li>Environmental: IP67 waterproof rating</li></ul>', 'SPC-GL722-001', 4999.00, 5999.00, 4, 5, true, true, true, 10, '["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400"]', '["spectra", "laser-level", "dual-grade", "construction"]', 'Spectra Precision GL722 Dual Grade Laser Level', 'Professional dual grade laser for construction with automatic leveling and 600m working range.'),

('Leica Rugby 640 Laser Level', 'leica-rugby-640-laser-level-outdoor-construction', 'Rugged outdoor laser level for construction and grading applications. Superior visibility and reliability in demanding conditions.', '<h3>Technical Specifications</h3><ul><li>Accuracy: ±1.5mm at 30m</li><li>Range: 640m with receiver</li><li>Visibility: Excellent in bright sunlight</li><li>Drop Rating: 1m onto concrete</li><li>Dust/Water: IP67 protection</li><li>Remote Control: 100m operating range</li></ul>', 'LCA-RG640-001', 2999.00, 3499.00, 4, 2, true, false, true, 18, '["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400"]', '["leica", "rugby", "laser-level", "outdoor"]', 'Leica Rugby 640 Laser Level - Outdoor Construction', 'Rugged outdoor laser level for construction with superior visibility and 640m range capability.'),

-- GPS Handheld Devices (Category 5)
('Garmin Montana 700i Handheld GPS', 'garmin-montana-700i-handheld-gps-inreach', 'Advanced handheld GPS with inReach satellite communication. Perfect for remote surveying and emergency communication.', '<h3>Technical Specifications</h3><ul><li>Display: 5" color touchscreen</li><li>GPS Accuracy: <3m typical</li><li>Battery Life: 18 hours GPS mode</li><li>inReach: Two-way satellite messaging</li><li>Memory: 16GB internal storage</li><li>Environmental: IPX7 water rating</li></ul>', 'GAR-MT700I-001', 799.00, 899.00, 5, 6, true, true, true, 25, '["https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400"]', '["garmin", "handheld", "gps", "inreach", "satellite"]', 'Garmin Montana 700i Handheld GPS - inReach Satellite', 'Advanced handheld GPS with inReach satellite communication for remote surveying and emergency situations.'),

('Trimble TDC7 Data Collector', 'trimble-tdc7-data-collector-android-surveying', 'Professional Android data collector designed for surveying and GIS applications. Rugged design with all-day battery life.', '<h3>Technical Specifications</h3><ul><li>Display: 7" high-brightness touchscreen</li><li>Operating System: Android 9</li><li>Battery: 14+ hours continuous use</li><li>Connectivity: Wi-Fi, Bluetooth, cellular</li><li>Environmental: IP65 dust/water protection</li><li>Storage: 128GB internal memory</li></ul>', 'TRM-TDC7-001', 3999.00, 4499.00, 5, 1, true, false, true, 8, '["https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400"]', '["trimble", "data-collector", "android", "surveying"]', 'Trimble TDC7 Data Collector - Android Surveying', 'Professional Android data collector designed for surveying with rugged design and all-day battery life.'),

-- Drone Surveying Equipment (Category 6)
('DJI Phantom 4 RTK Drone', 'dji-phantom-4-rtk-drone-surveying-mapping', 'Professional surveying and mapping drone with RTK GNSS for centimeter-level accuracy. Perfect for aerial data collection.', '<h3>Technical Specifications</h3><ul><li>Camera: 20MP 1" CMOS sensor</li><li>RTK Accuracy: 1cm horizontal, 1.5cm vertical</li><li>Flight Time: 30 minutes maximum</li><li>Max Speed: 58 km/h (Sport mode)</li><li>Operating Range: 7km transmission</li><li>Obstacle Sensing: 5-direction detection</li></ul>', 'DJI-P4RTK-001', 8999.00, 9999.00, 6, 7, true, true, true, 3, '["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400"]', '["dji", "phantom", "rtk", "drone", "surveying", "mapping"]', 'DJI Phantom 4 RTK Drone - Surveying & Mapping', 'Professional surveying drone with RTK GNSS for centimeter-level accuracy in aerial data collection.'),

('DJI Matrice 300 RTK Survey', 'dji-matrice-300-rtk-survey-enterprise-drone', 'Enterprise-grade surveying drone with advanced flight intelligence and payload flexibility. Ultimate solution for professional mapping.', '<h3>Technical Specifications</h3><ul><li>Flight Time: 55 minutes (no payload)</li><li>RTK Positioning: Real-time centimeter accuracy</li><li>Max Payload: 2.7kg</li><li>Operating Temperature: -20°C to +50°C</li><li>Transmission: 15km OcuSync Enterprise</li><li>AI Features: Smart inspection modes</li></ul>', 'DJI-M300RTK-001', 15999.00, 17999.00, 6, 7, true, true, true, 2, '["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400"]', '["dji", "matrice", "enterprise", "rtk", "professional"]', 'DJI Matrice 300 RTK Survey - Enterprise Drone', 'Enterprise-grade surveying drone with advanced flight intelligence for professional mapping applications.'),

-- Survey Software (Category 7)
('Carlson SurvCE Data Collection Software', 'carlson-survce-data-collection-software-field', 'Comprehensive field data collection software for total stations and GNSS receivers. Industry-standard surveying solution.', '<h3>Features</h3><ul><li>Device Support: 400+ instruments supported</li><li>COGO Functions: Complete coordinate geometry</li><li>Real-time Maps: CAD-quality field maps</li><li>Data Export: Multiple format support</li><li>Stakeout: Advanced staking routines</li><li>Network RTK: Full NTRIP support</li></ul>', 'CRL-SURVCE-001', 1999.00, 2499.00, 7, 12, true, false, true, 50, '["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400"]', '["carlson", "survce", "software", "data-collection"]', 'Carlson SurvCE Data Collection Software - Field Surveying', 'Comprehensive field data collection software supporting 400+ instruments for professional surveying.'),

('Trimble Access Field Software', 'trimble-access-field-software-surveying-solution', 'Professional field software for Trimble surveying instruments. Streamlined workflows for maximum productivity.', '<h3>Features</h3><ul><li>Integrated Workflows: GNSS and optical surveys</li><li>Real-time QA/QC: Instant data validation</li><li>Cloud Connectivity: Trimble Connect integration</li><li>Survey Styles: Customizable measurement styles</li><li>Reporting: Field-to-finish reporting</li><li>Multi-language: Global language support</li></ul>', 'TRM-ACCESS-001', 2499.00, 2999.00, 7, 1, true, true, true, 30, '["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400"]', '["trimble", "access", "field-software", "surveying"]', 'Trimble Access Field Software - Surveying Solution', 'Professional field software for Trimble instruments with integrated workflows and real-time QA/QC.'),

-- Measuring Tapes & Tools (Category 8)
('Leica Disto X4 Laser Rangefinder', 'leica-disto-x4-laser-rangefinder-outdoor', 'Professional laser distance meter with Bluetooth and outdoor measurement capability. Perfect for construction and surveying.', '<h3>Technical Specifications</h3><ul><li>Range: 0.05m to 150m</li><li>Accuracy: ±1.0mm typical</li><li>Bluetooth: Smart connectivity</li><li>Display: 2.4" color display</li><li>Battery: Li-Ion rechargeable</li><li>Environmental: IP65 protection</li></ul>', 'LCA-DISTOX4-001', 899.00, 999.00, 8, 2, true, false, true, 30, '["https://images.unsplash.com/photo-1609205801107-4a2dc63b7777?w=400"]', '["leica", "disto", "laser", "rangefinder", "bluetooth"]', 'Leica Disto X4 Laser Rangefinder - Outdoor Measurement', 'Professional laser distance meter with Bluetooth connectivity for outdoor construction and surveying applications.'),

('Professional Fiberglass Measuring Tape 100m', 'professional-fiberglass-measuring-tape-100m-metric', 'Heavy-duty fiberglass measuring tape for long-distance surveying measurements. Accurate and durable for field use.', '<h3>Features</h3><ul><li>Length: 100 meters</li><li>Material: Reinforced fiberglass</li><li>Markings: Metric graduation</li><li>Accuracy: ±3mm per 100m</li><li>Handle: Ergonomic ABS case</li><li>Durability: Weather resistant coating</li></ul>', 'PRO-TAPE100-001', 199.00, 249.00, 8, 11, true, false, true, 45, '["https://images.unsplash.com/photo-1609205801107-4a2dc63b7777?w=400"]', '["measuring-tape", "fiberglass", "100m", "surveying"]', 'Professional Fiberglass Measuring Tape 100m - Surveying Grade', 'Heavy-duty fiberglass measuring tape for accurate long-distance surveying measurements up to 100 meters.'),

-- Safety Equipment (Category 9)
('Hi-Vis Surveyor Safety Vest Class 2', 'hi-vis-surveyor-safety-vest-class-2-ansi', 'ANSI Class 2 high-visibility safety vest designed specifically for surveying professionals. Multiple pockets for equipment.', '<h3>Features</h3><ul><li>Compliance: ANSI/ISEA 107-2015 Class 2</li><li>Material: Breathable polyester mesh</li><li>Pockets: 10 specialized tool pockets</li><li>Closure: Heavy-duty zipper front</li><li>Sizes: S-5XL available</li><li>Colors: Orange or Yellow available</li></ul>', 'SAF-VEST-CL2-001', 89.00, 119.00, 9, 11, true, false, true, 100, '["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400"]', '["safety-vest", "hi-vis", "surveyor", "ansi-class-2"]', 'Hi-Vis Surveyor Safety Vest Class 2 - ANSI Compliant', 'ANSI Class 2 high-visibility safety vest designed for surveying professionals with specialized tool pockets.'),

('Professional Hard Hat with Chinstrap', 'professional-hard-hat-chinstrap-surveying-safety', 'ANSI Z89.1 certified hard hat with adjustable chinstrap for surveying and construction safety. Lightweight yet durable protection.', '<h3>Features</h3><ul><li>Certification: ANSI Z89.1 Type I</li><li>Material: High-density polyethylene</li><li>Suspension: 6-point ratchet adjustment</li><li>Chinstrap: Adjustable elastic strap</li><li>Ventilation: Side air vents</li><li>Colors: White, yellow, orange available</li></ul>', 'SAF-HHAT-001', 45.00, 59.00, 9, 11, true, false, true, 80, '["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400"]', '["hard-hat", "safety", "ansi", "surveying", "construction"]', 'Professional Hard Hat with Chinstrap - ANSI Certified', 'ANSI Z89.1 certified hard hat with adjustable chinstrap for surveying and construction safety applications.'),

-- Tripods & Accessories (Category 10)
('Heavy Duty Aluminum Survey Tripod', 'heavy-duty-aluminum-survey-tripod-professional', 'Professional-grade aluminum tripod for total stations and GNSS equipment. Adjustable height with quick-release leg locks.', '<h3>Technical Specifications</h3><ul><li>Material: Lightweight aluminum construction</li><li>Height Range: 1.0m to 1.65m</li><li>Head Type: 5/8" x 11 thread</li><li>Leg Locks: Quick-release flip locks</li><li>Weight: 2.8kg</li><li>Load Capacity: 8kg maximum</li></ul>', 'TRP-ALU-HD-001', 399.00, 499.00, 10, 11, true, false, true, 25, '["https://images.unsplash.com/photo-1609205801107-4a2dc63b7777?w=400"]', '["tripod", "aluminum", "survey", "professional", "heavy-duty"]', 'Heavy Duty Aluminum Survey Tripod - Professional Grade', 'Professional aluminum tripod for total stations and GNSS equipment with quick-release leg locks and 8kg capacity.'),

('Leica GZR3 360° Reflector Prism', 'leica-gzr3-360-degree-reflector-prism-surveying', 'High-precision 360° reflector prism for total station measurements. Superior accuracy and durability for professional surveying.', '<h3>Technical Specifications</h3><ul><li>Prism Type: 360° circular prism</li><li>Accuracy: ±1mm + 1ppm</li><li>Range: Up to 3500m</li><li>Mount: 5/8" x 11 thread</li><li>Material: Precision optical glass</li><li>Environmental: Shock resistant housing</li></ul>', 'LCA-GZR3-001', 899.00, 1099.00, 10, 2, true, true, true, 15, '["https://images.unsplash.com/photo-1609205801107-4a2dc63b7777?w=400"]', '["leica", "prism", "reflector", "360-degree", "surveying"]', 'Leica GZR3 360° Reflector Prism - Surveying Precision', 'High-precision 360° reflector prism for total station measurements with superior accuracy up to 3500m range.'),

('Carbon Fiber Survey Pole 2m', 'carbon-fiber-survey-pole-2m-telescopic-lightweight', 'Lightweight carbon fiber survey pole with telescopic design. Perfect for GNSS surveying and prism mounting applications.', '<h3>Features</h3><ul><li>Material: High-strength carbon fiber</li><li>Length: Telescopic 1.0m to 2.0m</li><li>Thread: 5/8" x 11 TPI</li><li>Weight: 580g total weight</li><li>Locking: Twist-lock segments</li><li>Graduations: Metric markings</li></ul>', 'POL-CF-2M-001', 299.00, 349.00, 10, 11, true, false, true, 35, '["https://images.unsplash.com/photo-1609205801107-4a2dc63b7777?w=400"]', '["survey-pole", "carbon-fiber", "telescopic", "lightweight"]', 'Carbon Fiber Survey Pole 2m - Telescopic Lightweight', 'Lightweight carbon fiber survey pole with telescopic design for GNSS surveying and prism mounting applications.'),

-- Additional GNSS Products
('CHC P5E GNSS RTK System', 'chc-p5e-gnss-rtk-system-professional-surveying', 'Professional GNSS RTK system with advanced signal processing and long-range RTK capabilities. Excellent value for professional surveying.', '<h3>Technical Specifications</h3><ul><li>Constellations: GPS, GLONASS, Galileo, BeiDou</li><li>RTK Accuracy: 8mm + 1ppm horizontal</li><li>Channels: 965 channels</li><li>RTK Range: 60km baseline</li><li>Battery: 12+ hours operation</li><li>Communication: Built-in 4G, Wi-Fi, Bluetooth</li></ul>', 'CHC-P5E-001', 7999.00, 9999.00, 1, 11, true, false, true, 6, '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400"]', '["chc", "gnss", "rtk", "professional", "value"]', 'CHC P5E GNSS RTK System - Professional Surveying', 'Professional GNSS RTK system with advanced signal processing and 60km baseline capability for surveying applications.'),

('South Galaxy G1 GNSS Receiver', 'south-galaxy-g1-gnss-receiver-plus-technology', 'Advanced GNSS receiver with Galaxy PLUS technology for enhanced signal tracking in challenging environments.', '<h3>Technical Specifications</h3><ul><li>Technology: Galaxy PLUS signal processing</li><li>Accuracy: 3mm + 0.1ppm RTK</li><li>Channels: 555 channels all-in-view</li><li>Tilt Compensation: Optional IMU module</li><li>Battery: 15+ hours continuous</li><li>Environmental: IP68 waterproof</li></ul>', 'STH-G1-001', 8999.00, 10999.00, 1, 10, true, false, true, 4, '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400"]', '["south", "galaxy", "gnss", "plus-technology"]', 'South Galaxy G1 GNSS Receiver - PLUS Technology', 'Advanced GNSS receiver with Galaxy PLUS technology for enhanced signal tracking in challenging environments.'),

-- Additional Total Stations
('Nikon XF Total Station', 'nikon-xf-total-station-hybrid-imaging-technology', 'Innovative total station with hybrid imaging technology combining optical and digital measurement methods for enhanced productivity.', '<h3>Technical Specifications</h3><ul><li>Angle Accuracy: 2" (0.6mgon)</li><li>Distance Accuracy: 2mm + 2ppm</li><li>Hybrid Imaging: Optical + digital camera</li><li>Reflectorless Range: 2000m</li><li>Display: 5.7" color touchscreen</li><li>Operating Time: 24 hours continuous</li></ul>', 'NKN-XF-001', 22999.00, 25999.00, 2, 8, true, false, true, 3, '["https://images.unsplash.com/photo-1581094289206-c0ddd9e21b0e?w=400"]', '["nikon", "total-station", "hybrid", "imaging"]', 'Nikon XF Total Station - Hybrid Imaging Technology', 'Innovative total station with hybrid imaging technology for enhanced productivity in surveying applications.'),

-- Additional Handheld GPS
('Trimble Geo 7X Handheld', 'trimble-geo-7x-handheld-gis-data-collector', 'Professional GIS data collector with integrated camera and high-accuracy GPS. Perfect for field data collection and mapping.', '<h3>Technical Specifications</h3><ul><li>GPS Accuracy: Sub-meter out of box</li><li>Camera: 8MP with geotagging</li><li>Display: 4.3" sunlight-readable</li><li>Operating System: Windows Mobile</li><li>Battery: 8+ hours field use</li><li>Environmental: IP67 rating</li></ul>', 'TRM-GEO7X-001', 4999.00, 5999.00, 5, 1, true, false, true, 5, '["https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400"]', '["trimble", "geo7x", "gis", "data-collector", "handheld"]', 'Trimble Geo 7X Handheld - GIS Data Collector', 'Professional GIS data collector with integrated camera and high-accuracy GPS for field data collection.');

-- Insert Blog Posts with SEO content
INSERT INTO blog_posts (title, slug, content, excerpt, author, is_published, featured_image, tags, meta_title, meta_description, published_at) VALUES
('Understanding GNSS Technology in Modern Surveying', 'understanding-gnss-technology-modern-surveying-applications', '<h2>The Evolution of GNSS Technology</h2><p>Global Navigation Satellite System (GNSS) technology has revolutionized the surveying industry, providing unprecedented accuracy and efficiency in positioning applications...</p>', 'Comprehensive guide to GNSS technology and its applications in modern surveying practices.', 'CV. Aprinia Geosat Technical Team', true, 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800', '["gnss", "surveying", "technology", "gps"]', 'Understanding GNSS Technology in Modern Surveying Applications', 'Comprehensive guide to GNSS technology, applications, and benefits in modern surveying and mapping practices.', NOW() - INTERVAL '7 days'),

('Total Station vs GNSS: Choosing the Right Equipment', 'total-station-vs-gnss-choosing-right-surveying-equipment', '<h2>Comparing Survey Technologies</h2><p>When planning a surveying project, one of the most important decisions is choosing between total station and GNSS technology...</p>', 'Expert comparison guide for selecting between total station and GNSS equipment for different surveying projects.', 'CV. Aprinia Geosat Technical Team', true, 'https://images.unsplash.com/photo-1581094289206-c0ddd9e21b0e?w=800', '["total-station", "gnss", "comparison", "equipment"]', 'Total Station vs GNSS: Choosing the Right Surveying Equipment', 'Expert comparison guide for selecting between total station and GNSS equipment for optimal surveying results.', NOW() - INTERVAL '14 days'),

('Best Practices for RTK GNSS Surveying', 'best-practices-rtk-gnss-surveying-accuracy-tips', '<h2>Maximizing RTK GNSS Accuracy</h2><p>Real-Time Kinematic (RTK) GNSS surveying offers centimeter-level accuracy, but achieving optimal results requires following established best practices...</p>', 'Professional tips and best practices for achieving maximum accuracy with RTK GNSS surveying systems.', 'CV. Aprinia Geosat Technical Team', true, 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800', '["rtk", "gnss", "best-practices", "accuracy"]', 'Best Practices for RTK GNSS Surveying - Accuracy Tips', 'Professional tips and best practices for achieving maximum accuracy with RTK GNSS surveying systems and equipment.', NOW() - INTERVAL '21 days');
