-- Additional Indonesian Products for GeoTech Store (Fixed Pricing)
-- High-quality SEO-optimized content in Indonesian with USD pricing

-- Insert more comprehensive product catalog with corrected price format (USD)
INSERT INTO products (name, slug, description, short_description, sku, price, compare_price, cost_price, category_id, brand_id, is_active, is_featured, in_stock, stock_quantity, weight, dimensions, images, tags, meta_title, meta_description) VALUES

-- GPS & GNSS Products
('Trimble R10 Model 2 GNSS Receiver', 'trimble-r10-model-2-gnss-receiver-indonesia', 'Receiver GNSS Trimble R10 Model 2 adalah solusi survei terdepan dengan teknologi IMU terintegrasi dan kompensasi kemiringan hingga 30 derajat. Dilengkapi dengan teknologi ProPoint GNSS dan dukungan konstelasi multi-satelit untuk akurasi sub-sentimeter. Ideal untuk survei topografi, pemetaan kadaster, dan aplikasi konstruksi di Indonesia dengan dukungan korreksi RTK berbasis internet.', 'Receiver GNSS profesional dengan kompensasi kemiringan dan teknologi IMU terintegrasi', 'TRM-R10M2-IDN-001', 18900.00, 21000.00, 14500.00, 1, 1, true, true, true, 3, 2.1, '{"length": 19, "width": 19, "height": 10.5}', '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["gnss", "gps", "trimble", "survei", "pemetaan", "rtk", "indonesia"]', 'Trimble R10 Model 2 GNSS Receiver Indonesia - Survei Presisi Tinggi', 'Beli Trimble R10 Model 2 GNSS Receiver di Indonesia. Akurasi sub-sentimeter, kompensasi kemiringan 30°, teknologi IMU terintegrasi. Garansi resmi dan layanan purna jual terbaik.'),

('Leica GS16 UltraMax GNSS Receiver', 'leica-gs16-ultramax-gnss-receiver-indonesia', 'Leica GS16 UltraMax adalah receiver GNSS revolusioner dengan teknologi tilt compensation dan visual positioning yang memungkinkan pengukuran presisi tanpa perlu mendirikan alat secara vertikal. Dilengkapi dengan kamera terintegrasi untuk dokumentasi titik dan teknologi SmartLink untuk komunikasi jarak jauh. Cocok untuk survei kadaster, topografi, dan monitoring deformasi di seluruh Indonesia.', 'Receiver GNSS revolusioner dengan visual positioning dan tilt compensation 60°', 'LCA-GS16UM-IDN-001', 22500.00, 25000.00, 17500.00, 1, 2, true, true, true, 2, 1.9, '{"length": 18.5, "width": 18.5, "height": 9.2}', '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["leica", "gnss", "visual-positioning", "tilt-compensation", "survei", "indonesia"]', 'Leica GS16 UltraMax GNSS Indonesia - Visual Positioning Technology', 'Jual Leica GS16 UltraMax GNSS Receiver Indonesia. Teknologi visual positioning, tilt compensation 60°, akurasi mm. Distributor resmi dengan layanan kalibrasi dan training.'),

('Topcon HiPer SR GNSS Base/Rover System', 'topcon-hiper-sr-gnss-base-rover-system-indonesia', 'Sistem GNSS Base/Rover Topcon HiPer SR memberikan solusi RTK berkinerja tinggi dengan jangkauan baseline hingga 60km. Dilengkapi dengan teknologi Fence Antenna untuk mengurangi multipath dan Universal Tracking Channels untuk tracking semua sinyal satelit. Ideal untuk proyek infrastruktur besar, survei tambang, dan pemetaan skala regional di Indonesia dengan dukungan jaringan CORS.', 'Sistem GNSS Base/Rover dengan jangkauan RTK hingga 60km dan teknologi Fence Antenna', 'TPC-HIPERSR-IDN-001', 16500.00, 18500.00, 12500.00, 1, 3, true, false, true, 4, 2.8, '{"length": 20, "width": 20, "height": 11}', '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["topcon", "gnss", "base-rover", "rtk", "fence-antenna", "survei", "indonesia"]', 'Topcon HiPer SR GNSS Base/Rover Indonesia - RTK 60km Range', 'Sistem Topcon HiPer SR GNSS Base/Rover Indonesia. Jangkauan RTK 60km, Fence Antenna technology, Universal Tracking. Solusi survei profesional dengan support teknis lokal.'),

-- Total Station Products  
('Leica TS16 P Robotic Total Station', 'leica-ts16-p-robotic-total-station-indonesia', 'Total Station Robotik Leica TS16 P menawarkan akurasi angular 1" dan jarak 1mm + 1.5ppm dengan teknologi ATRplus dan PowerSearch untuk tracking target otomatis. Dilengkapi dengan Captivate software untuk workflow yang efisien dan AutoHeight untuk pengukuran tinggi otomatis. Solusi terbaik untuk survei konstruksi, monitoring struktur, dan pemetaan detail di Indonesia dengan dukungan training dan kalibrasi resmi.', 'Total Station robotik presisi tinggi dengan AutoHeight dan ATRplus technology', 'LCA-TS16P-IDN-001', 45000.00, 50000.00, 35000.00, 2, 2, true, true, true, 2, 5.4, '{"length": 35, "width": 25, "height": 30}', '["https://images.unsplash.com/photo-1581094222043-8318c5f982ec?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["leica", "total-station", "robotik", "atrplus", "autoheight", "survei", "indonesia"]', 'Leica TS16 P Robotic Total Station Indonesia - Akurasi 1 Detik', 'Jual Leica TS16 P Robotic Total Station Indonesia. Akurasi angular 1", ATRplus tracking, AutoHeight technology. Distributor resmi dengan training dan support teknis.'),

('Topcon GT-1200 Series Robotic Total Station', 'topcon-gt-1200-robotic-total-station-indonesia', 'Total Station Robotik Topcon GT-1200 Series menghadirkan teknologi UltraSonic motors untuk pergerakan halus dan presisi tinggi. Dilengkapi dengan UltraTrac technology untuk tracking target yang superior dan TSshield security system. Akurasi angular hingga 1" dan jarak 2mm + 2ppm menjadikannya pilihan ideal untuk proyek konstruksi presisi tinggi, survei infrastruktur, dan monitoring deformasi di Indonesia.', 'Total Station robotik dengan UltraSonic motors dan UltraTrac technology', 'TPC-GT1200-IDN-001', 42000.00, 47000.00, 32000.00, 2, 3, true, true, true, 3, 5.8, '{"length": 38, "width": 28, "height": 32}', '["https://images.unsplash.com/photo-1581094222043-8318c5f982ec?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["topcon", "total-station", "robotik", "ultrasonic", "ultratrac", "survei", "indonesia"]', 'Topcon GT-1200 Robotic Total Station Indonesia - UltraSonic Technology', 'Beli Topcon GT-1200 Robotic Total Station Indonesia. UltraSonic motors, UltraTrac tracking, akurasi 1". Garansi resmi dan pelatihan operator tersedia.'),

('Trimble S9 HP Robotic Total Station', 'trimble-s9-hp-robotic-total-station-indonesia', 'Trimble S9 HP Robotic Total Station memberikan performa terdepan dengan akurasi angular 0.5" dan teknologi MagDrive servo motors untuk kecepatan tracking hingga 30°/detik. Dilengkapi dengan FineLock technology untuk penguncian target presisi dan VISION technology untuk imaging dan dokumentasi. Ideal untuk survei engineering, monitoring struktur presisi tinggi, dan aplikasi metrologi industri di Indonesia.', 'Total Station robotik premium dengan akurasi 0.5" dan MagDrive technology', 'TRM-S9HP-IDN-001', 65000.00, 72000.00, 50000.00, 2, 1, true, true, true, 1, 5.2, '{"length": 36, "width": 26, "height": 31}', '["https://images.unsplash.com/photo-1581094222043-8318c5f982ec?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["trimble", "total-station", "robotik", "magdrive", "finelock", "vision", "indonesia"]', 'Trimble S9 HP Robotic Total Station Indonesia - Akurasi 0.5 Detik', 'Trimble S9 HP Robotic Total Station Indonesia. Akurasi angular 0.5", MagDrive servo, FineLock technology. Solusi premium untuk survei presisi tinggi dan metrologi industri.'),

-- Laser Level Products
('Leica Rugby 880 Rotating Laser Level', 'leica-rugby-880-rotating-laser-level-indonesia', 'Laser Level Rotary Leica Rugby 880 menawarkan jangkauan hingga 600m diameter dengan akurasi ±1mm pada 30m. Dilengkapi dengan teknologi IP67 untuk ketahanan terhadap air dan debu, serta dual grade capability untuk aplikasi sloping. Cocok untuk konstruksi gedung bertingkat, jalan raya, saluran irigasi, dan proyek infrastruktur besar di Indonesia dengan dukungan receiver ClodeSeekerdigital dan remote control.', 'Laser level rotary profesional dengan jangkauan 600m dan dual grade capability', 'LCA-RUG880-IDN-001', 4500.00, 5200.00, 3500.00, 3, 2, true, false, true, 6, 2.1, '{"length": 25, "width": 15, "height": 12}', '["https://images.unsplash.com/photo-1581092335878-1077f6497b7e?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["leica", "laser-level", "rotary", "konstruksi", "waterpass", "indonesia"]', 'Leica Rugby 880 Rotating Laser Level Indonesia - Jangkauan 600m', 'Jual Leica Rugby 880 Rotating Laser Level Indonesia. Jangkauan 600m, akurasi ±1mm/30m, IP67 rating. Ideal untuk konstruksi dan infrastruktur dengan garansi resmi.'),

('Topcon RL-H5A Self-Leveling Rotating Laser', 'topcon-rl-h5a-self-leveling-rotating-laser-indonesia', 'Laser Level Self-Leveling Topcon RL-H5A memberikan jangkauan hingga 800m diameter dengan akurasi ±10" dan kecepatan rotasi variabel 0-600 RPM. Dilengkapi dengan teknologi magnetic dampening untuk stabilitas superior dan drop protection untuk ketahanan impact. Solusi ideal untuk konstruksi komersial, residential, dan proyek sipil di Indonesia dengan dukungan remote control LS-80L dan receiver compatible.', 'Laser level self-leveling dengan jangkauan 800m dan magnetic dampening', 'TPC-RLH5A-IDN-001', 3800.00, 4200.00, 2800.00, 3, 3, true, false, true, 8, 1.9, '{"length": 24, "width": 14, "height": 11}', '["https://images.unsplash.com/photo-1581092335878-1077f6497b7e?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["topcon", "laser-level", "self-leveling", "magnetic-dampening", "konstruksi", "indonesia"]', 'Topcon RL-H5A Self-Leveling Laser Indonesia - Jangkauan 800m', 'Beli Topcon RL-H5A Self-Leveling Rotating Laser Indonesia. Jangkauan 800m, magnetic dampening, variable speed. Garansi resmi dan training tersedia.'),

-- Theodolite Products
('Leica Builder 500 Digital Theodolite', 'leica-builder-500-digital-theodolite-indonesia', 'Theodolite Digital Leica Builder 500 menawarkan akurasi angular 5" dengan kompensator dual-axis dan display LCD yang mudah dibaca. Dilengkapi dengan absolute encoders untuk pengukuran yang konsisten dan teknologi endless drives untuk tracking yang smooth. Ideal untuk survei property, layout konstruksi, dan pengukuran sudut presisi di proyek-proyek Indonesia dengan dukungan software transfer data dan manual bahasa Indonesia.', 'Theodolite digital dengan akurasi 5" dan kompensator dual-axis', 'LCA-BLD500-IDN-001', 2800.00, 3200.00, 2200.00, 6, 2, true, false, true, 5, 4.2, '{"length": 30, "width": 20, "height": 25}', '["https://images.unsplash.com/photo-1581094222043-8318c5f982ec?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["leica", "theodolite", "digital", "kompensator", "absolute-encoder", "indonesia"]', 'Leica Builder 500 Digital Theodolite Indonesia - Akurasi 5 Detik', 'Jual Leica Builder 500 Digital Theodolite Indonesia. Akurasi angular 5", dual-axis compensator, absolute encoders. Solusi survei property dan konstruksi dengan garansi resmi.');

-- Insert more categories if needed
INSERT INTO categories (name, slug, description, image_url, is_active, sort_order) VALUES
('Aksesoris Lapangan', 'aksesoris-lapangan-survei-indonesia', 'Aksesoris dan perlengkapan lapangan untuk mendukung kegiatan survei dan pemetaan di Indonesia', '/placeholder.svg?height=80&width=80&text=🧰', true, 11),
('Software GIS', 'software-gis-pemetaan-indonesia', 'Software GIS dan pemetaan untuk analisis data spasial dan visualisasi peta Indonesia', '/placeholder.svg?height=80&width=80&text=💻', true, 12),
('Drone Pemetaan', 'drone-pemetaan-aerial-survey-indonesia', 'Drone dan UAV untuk survei aerial dan pemetaan fotogrametri di Indonesia', '/placeholder.svg?height=80&width=80&text=🚁', true, 13);

-- Insert additional brands
INSERT INTO brands (name, slug, description, logo_url, is_active) VALUES
('Hi-Target', 'hi-target-surveying-indonesia', 'Solusi survei dan pemetaan presisi tinggi dari Hi-Target untuk pasar Indonesia', '/placeholder.svg?height=60&width=120&text=Hi-Target', true),
('South Surveying', 'south-surveying-instruments-indonesia', 'Instrumen survei berkualitas tinggi dari South Surveying dengan support lokal Indonesia', '/placeholder.svg?height=60&width=120&text=South', true),
('Stonex', 'stonex-positioning-solutions-indonesia', 'Teknologi positioning dan survei dari Stonex dengan distribusi resmi Indonesia', '/placeholder.svg?height=60&width=120&text=Stonex', true);

-- Continue with more products...
INSERT INTO products (name, slug, description, short_description, sku, price, compare_price, cost_price, category_id, brand_id, is_active, is_featured, in_stock, stock_quantity, weight, dimensions, images, tags, meta_title, meta_description) VALUES

-- More GNSS Products with Indonesian focus
('Hi-Target V200 GNSS RTK System', 'hi-target-v200-gnss-rtk-system-indonesia', 'Sistem GNSS RTK Hi-Target V200 memberikan solusi survei ekonomis dengan performa tinggi untuk pasar Indonesia. Dilengkapi dengan teknologi 965 channels tracking dan dukungan BDS, GPS, GLONASS, Galileo. Akurasi horizontal 8mm + 1ppm dan vertikal 15mm + 1ppm menjadikannya pilihan ideal untuk survei kadaster, topografi, dan proyek infrastruktur dengan budget terbatas namun hasil professional.', 'GNSS RTK system ekonomis dengan 965 channels dan dukungan multi-konstelasi', 'HIT-V200-IDN-001', 9500.00, 11000.00, 7500.00, 1, 4, true, false, true, 8, 1.7, '{"length": 17, "width": 17, "height": 8.5}', '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["hi-target", "gnss", "rtk", "965-channels", "ekonomis", "survei", "indonesia"]', 'Hi-Target V200 GNSS RTK Indonesia - Solusi Ekonomis 965 Channels', 'Hi-Target V200 GNSS RTK System Indonesia. 965 channels, multi-konstelasi, akurasi 8mm+1ppm. Solusi survei ekonomis dengan performa professional dan support lokal.'),

('South Galaxy G1 Plus GNSS Receiver', 'south-galaxy-g1-plus-gnss-receiver-indonesia', 'Receiver GNSS South Galaxy G1 Plus menghadirkan teknologi terdepan dengan 1408 channels tracking dan dukungan sinyal L1/L2/L5. Dilengkapi dengan IMU compensation dan teknologi anti-jamming untuk lingkungan challenging di Indonesia. Akurasi RTK horizontal 8mm + 0.5ppm dan vertikal 15mm + 0.5ppm menjadikannya solusi handal untuk survei presisi tinggi, pemetaan kadaster, dan monitoring deformasi struktur di seluruh nusantara.', 'GNSS receiver dengan 1408 channels, IMU compensation, dan teknologi anti-jamming', 'STH-G1PLUS-IDN-001', 12500.00, 14000.00, 9500.00, 1, 5, true, true, true, 6, 1.6, '{"length": 16.8, "width": 16.8, "height": 8.2}', '["https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["south", "gnss", "galaxy", "1408-channels", "imu", "anti-jamming", "indonesia"]', 'South Galaxy G1 Plus GNSS Indonesia - 1408 Channels IMU Compensation', 'South Galaxy G1 Plus GNSS Receiver Indonesia. 1408 channels, IMU compensation, anti-jamming technology. Solusi presisi tinggi untuk survei professional dengan garansi resmi.'),

-- Rangefinder Products
('Leica Disto X4 Laser Rangefinder', 'leica-disto-x4-laser-rangefinder-indonesia', 'Laser Rangefinder Leica Disto X4 menawarkan akurasi pengukuran jarak hingga ±1mm dengan jangkauan 150m. Dilengkapi dengan point-to-point technology untuk pengukuran tidak langsung dan IP65 rating untuk ketahanan outdoor. Fitur digital viewfinder memudahkan pengukuran dalam cahaya terang, sedangkan Bluetooth connectivity memungkinkan transfer data ke smartphone. Ideal untuk as-built survey, pengukuran facade building, dan inventory space di proyek-proyek Indonesia.', 'Laser rangefinder presisi tinggi dengan point-to-point technology dan Bluetooth', 'LCA-DISTOX4-IDN-001', 1850.00, 2100.00, 1400.00, 7, 2, true, false, true, 12, 0.2, '{"length": 14.3, "width": 5.8, "height": 2.8}', '["https://images.unsplash.com/photo-1581092335878-1077f6497b7e?w=400", "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400"]', '["leica", "laser-rangefinder", "point-to-point", "bluetooth", "as-built", "indonesia"]', 'Leica Disto X4 Laser Rangefinder Indonesia - Akurasi 1mm Jangkauan 150m', 'Jual Leica Disto X4 Laser Rangefinder Indonesia. Akurasi ±1mm, jangkauan 150m, point-to-point technology, Bluetooth. Solusi pengukuran profesional dengan garansi resmi.');

-- Update some existing products with better Indonesian content
UPDATE products SET 
  description = 'Receiver GNSS Trimble R12i adalah solusi survei profesional dengan teknologi IMU terintegrasi untuk kompensasi kemiringan hingga 30 derajat. Dilengkapi dengan teknologi ProPoint GNSS dan dukungan konstelasi multi-satelit (GPS, GLONASS, Galileo, BeiDou) untuk akurasi sub-sentimeter. Cocok untuk survei topografi, pemetaan kadaster, monitoring deformasi, dan aplikasi konstruksi di Indonesia dengan dukungan jaringan CORS nasional dan layanan RTK berbasis internet.',
  meta_title = 'Trimble R12i GNSS Receiver Indonesia - Survei Profesional Akurasi Sub-Sentimeter',
  meta_description = 'Jual Trimble R12i GNSS Receiver Indonesia. Teknologi IMU, kompensasi kemiringan 30°, akurasi sub-sentimeter. Distributor resmi dengan garansi, training, dan support teknis lokal.',
  tags = '["trimble", "gnss", "r12i", "imu", "kompensasi-kemiringan", "survei", "pemetaan", "indonesia", "cors", "rtk"]'
WHERE id = 1;

UPDATE products SET
  description = 'Total Station Robotik Leica TS16 memberikan performa survei terdepan dengan akurasi angular 1" dan jarak 1mm + 1.5ppm. Dilengkapi dengan teknologi ATRplus untuk automatic target recognition dan AutoHeight untuk pengukuran tinggi otomatis tanpa reflector. Captivate software memberikan workflow yang intuitif, sedangkan PowerSearch memungkinkan pencarian target dalam radius 360°. Solusi ideal untuk survei konstruksi, monitoring struktur, as-built survey, dan pemetaan detail di proyek-proyek infrastruktur Indonesia.',
  meta_title = 'Leica TS16 Total Station Robotik Indonesia - Akurasi 1 Detik ATRplus Technology',
  meta_description = 'Leica TS16 Total Station Robotik Indonesia. Akurasi angular 1", ATRplus automatic tracking, AutoHeight technology. Distributor resmi dengan training operator dan support teknis.',
  tags = '["leica", "total-station", "ts16", "robotik", "atrplus", "autoheight", "captivate", "survei", "konstruksi", "indonesia"]'
WHERE name LIKE '%Leica TS16%';

COMMIT;
