-- GPS Store Database Seeding Script - Part 2
-- Additional products for complete GPS store inventory

-- Level Optik Products
INSERT INTO products (
    name, slug, description, short_description, sku, price, compare_price, cost_price,
    category_id, brand_id, is_active, is_featured, in_stock, stock_quantity, weight,
    dimensions, images, tags, meta_title, meta_description
) VALUES
('Leica NA720 Automatic Level', 'leica-na720-automatic-level', 
'Level optik otomatis Leica NA720 dengan akurasi 2.5mm/km dan magnification 20x. Dilengkapi dengan kompensator magnetik yang memberikan akurasi konsisten. Fokus minimum 0.6m dengan teropong berkualitas tinggi. Tahan debu dan air IP54. Cocok untuk survei konstruksi, leveling, dan aplikasi engineering yang membutuhkan akurasi tinggi.', 
'Level optik otomatis dengan akurasi 2.5mm/km', 
'LEI-NA720-LEVEL', 19900000, 21900000, 16000000, 
5, 3, true, true, true, 15, 1.6, 
'{"panjang": "20 cm", "lebar": "20 cm", "tinggi": "14 cm"}', 
'["/images/products/leica-na720-1.jpg", "/images/products/leica-na720-2.jpg"]', 
'["level optik", "otomatis", "akurasi 2.5mm", "magnification 20x", "survei konstruksi", "leveling"]', 
'Leica NA720 Automatic Level - Level Optik Otomatis dengan Akurasi 2.5mm/km', 
'Jual Leica NA720 Automatic Level dengan akurasi 2.5mm/km dan magnification 20x. Kompensator magnetik, IP54, cocok untuk survei konstruksi.'),

('Topcon AT-B4 Automatic Level', 'topcon-at-b4-automatic-level', 
'Level otomatis Topcon AT-B4 dengan akurasi 1.5mm/km dan magnification 24x. Dilengkapi dengan kompensator magnetik yang stabil dan reliable. Fokus minimum 0.3m dengan teropong berkualitas tinggi. Tahan debu dan air IP56. Cocok untuk survei konstruksi, monitoring, dan aplikasi engineering yang membutuhkan akurasi presisi.', 
'Level otomatis dengan akurasi 1.5mm/km dan magnification 24x', 
'TOP-ATB4-LEVEL', 17900000, 19900000, 14500000, 
5, 4, true, false, true, 22, 1.8, 
'{"panjang": "22 cm", "lebar": "22 cm", "tinggi": "15 cm"}', 
'["/images/products/topcon-at-b4-1.jpg", "/images/products/topcon-at-b4-2.jpg"]', 
'["level otomatis", "akurasi 1.5mm", "magnification 24x", "survei konstruksi", "monitoring", "engineering"]', 
'Topcon AT-B4 Automatic Level - Level Otomatis dengan Akurasi 1.5mm/km', 
'Beli Topcon AT-B4 Automatic Level dengan akurasi 1.5mm/km dan magnification 24x. Kompensator magnetik, IP56, cocok untuk survei konstruksi.'),

('Sokkia B40 Automatic Level', 'sokkia-b40-automatic-level', 
'Level otomatis Sokkia B40 dengan akurasi 2.0mm/km dan magnification 24x. Dilengkapi dengan kompensator magnetik yang memberikan stabilitas tinggi. Fokus minimum 0.5m dengan teropong berkualitas. Tahan debu dan air IP54. Cocok untuk survei topografi, konstruksi, dan aplikasi leveling dengan akurasi standar.', 
'Level otomatis dengan akurasi 2.0mm/km', 
'SOK-B40-LEVEL', 13900000, 15900000, 11000000, 
5, 5, true, true, true, 28, 1.4, 
'{"panjang": "19 cm", "lebar": "19 cm", "tinggi": "13 cm"}', 
'["/images/products/sokkia-b40-1.jpg", "/images/products/sokkia-b40-2.jpg"]', 
'["level otomatis", "akurasi 2.0mm", "magnification 24x", "survei topografi", "konstruksi", "leveling"]', 
'Sokkia B40 Automatic Level - Level Otomatis dengan Akurasi 2.0mm/km', 
'Jual Sokkia B40 Automatic Level dengan akurasi 2.0mm/km dan magnification 24x. Kompensator magnetik, IP54, cocok untuk survei topografi.'),

-- Laser Level Products
('Leica Rugby 610 Laser Level', 'leica-rugby-610-laser-level', 
'Laser level Leica Rugby 610 dengan teknologi dual-grade dan akurasi ±1.5mm/30m. Dilengkapi dengan self-leveling otomatis dan jangkauan hingga 600m dengan receiver. Laser merah dengan visibility tinggi. Tahan debu dan air IP67. Cocok untuk grading, excavation, dan aplikasi konstruksi outdoor yang membutuhkan akurasi tinggi.', 
'Laser level dual-grade dengan akurasi ±1.5mm/30m', 
'LEI-RUGBY610-LASER', 34900000, 37900000, 28000000, 
6, 3, true, true, true, 12, 2.8, 
'{"panjang": "24 cm", "lebar": "24 cm", "tinggi": "21 cm"}', 
'["/images/products/leica-rugby-610-1.jpg", "/images/products/leica-rugby-610-2.jpg"]', 
'["laser level", "dual-grade", "akurasi 1.5mm", "self-leveling", "grading", "excavation", "konstruksi"]', 
'Leica Rugby 610 Laser Level - Laser Level Dual-Grade dengan Akurasi ±1.5mm', 
'Beli Leica Rugby 610 Laser Level dengan teknologi dual-grade dan akurasi ±1.5mm/30m. Self-leveling, jangkauan 600m, IP67, cocok untuk grading.'),

('Topcon RL-H5A Laser Level', 'topcon-rl-h5a-laser-level', 
'Laser level Topcon RL-H5A dengan teknologi horizontal self-leveling dan akurasi ±10 arc second. Dilengkapi dengan dual-axis kompensator dan jangkauan hingga 800m dengan receiver. Laser merah dengan kecepatan rotasi variabel. Tahan debu dan air IP66. Cocok untuk leveling, grading, dan aplikasi konstruksi interior maupun eksterior.', 
'Laser level horizontal dengan akurasi ±10 arc second', 
'TOP-RLH5A-LASER', 24900000, 27900000, 20000000, 
6, 4, true, false, true, 18, 2.2, 
'{"panjang": "22 cm", "lebar": "22 cm", "tinggi": "18 cm"}', 
'["/images/products/topcon-rl-h5a-1.jpg", "/images/products/topcon-rl-h5a-2.jpg"]', 
'["laser level", "horizontal", "self-leveling", "akurasi 10 arc second", "leveling", "grading", "konstruksi"]', 
'Topcon RL-H5A Laser Level - Laser Level Horizontal dengan Akurasi ±10 Arc Second', 
'Jual Topcon RL-H5A Laser Level dengan teknologi horizontal self-leveling dan akurasi ±10 arc second. Jangkauan 800m, IP66, cocok untuk leveling.'),

('Spectra Precision GL722 Laser Level', 'spectra-precision-gl722-laser-level', 
'Laser level Spectra Precision GL722 dengan teknologi dual-grade dan akurasi ±1.5mm/30m. Dilengkapi dengan self-leveling otomatis dan remote control. Jangkauan hingga 700m dengan receiver. Laser merah dengan visibility tinggi. Tahan debu dan air IP67. Cocok untuk grading, slope work, dan aplikasi konstruksi yang membutuhkan dual-grade capability.', 
'Laser level dual-grade dengan remote control', 
'SPEC-GL722-LASER', 29900000, 32900000, 24000000, 
6, 9, true, true, true, 15, 2.5, 
'{"panjang": "23 cm", "lebar": "23 cm", "tinggi": "19 cm"}', 
'["/images/products/spectra-gl722-1.jpg", "/images/products/spectra-gl722-2.jpg"]', 
'["laser level", "dual-grade", "remote control", "akurasi 1.5mm", "grading", "slope work", "konstruksi"]', 
'Spectra Precision GL722 Laser Level - Laser Level Dual-Grade dengan Remote Control', 
'Beli Spectra Precision GL722 Laser Level dengan teknologi dual-grade dan remote control. Akurasi ±1.5mm/30m, jangkauan 700m, IP67.'),

-- Ranging Pole Products
('Leica GLS126 Carbon Ranging Pole', 'leica-gls126-carbon-ranging-pole', 
'Ranging pole carbon fiber Leica GLS126 dengan panjang 2.6m dan diameter 25mm. Dilengkapi dengan graduasi merah-putih setiap 10cm dan angka hitam. Ujung bawah dengan spike steel dan ujung atas dengan thread 5/8". Ringan dan kuat dengan berat hanya 0.8kg. Cocok untuk survei dengan GPS, total station, dan aplikasi pemetaan yang membutuhkan akurasi tinggi.', 
'Ranging pole carbon fiber 2.6m dengan graduasi presisi', 
'LEI-GLS126-POLE', 1999000, 2299000, 1600000, 
7, 3, true, true, true, 35, 0.8, 
'{"panjang": "260 cm", "diameter": "25 mm"}', 
'["/images/products/leica-gls126-1.jpg", "/images/products/leica-gls126-2.jpg"]', 
'["ranging pole", "carbon fiber", "graduasi presisi", "GPS", "total station", "pemetaan", "survei"]', 
'Leica GLS126 Carbon Ranging Pole - Ranging Pole Carbon Fiber 2.6m | Jual Leica', 
'Beli Leica GLS126 Carbon Ranging Pole dengan panjang 2.6m dan graduasi presisi. Carbon fiber ringan, spike steel, cocok untuk survei GPS dan total station.'),

('Topcon TP-2M Aluminum Ranging Pole', 'topcon-tp-2m-aluminum-ranging-pole', 
'Ranging pole aluminum Topcon TP-2M dengan panjang 2m dan diameter 25mm. Dilengkapi dengan graduasi merah-putih setiap 10cm dan angka hitam tebal. Ujung bawah dengan spike steel dan ujung atas dengan thread 5/8". Konstruksi aluminum yang tahan lama dengan berat 1.2kg. Cocok untuk survei topografi, konstruksi, dan aplikasi pemetaan standar.', 
'Ranging pole aluminum 2m dengan konstruksi tahan lama', 
'TOP-TP2M-POLE', 899000, 1099000, 700000, 
7, 4, true, false, true, 45, 1.2, 
'{"panjang": "200 cm", "diameter": "25 mm"}', 
'["/images/products/topcon-tp-2m-1.jpg", "/images/products/topcon-tp-2m-2.jpg"]', 
'["ranging pole", "aluminum", "konstruksi tahan lama", "survei topografi", "konstruksi", "pemetaan"]', 
'Topcon TP-2M Aluminum Ranging Pole - Ranging Pole Aluminum 2m Tahan Lama', 
'Jual Topcon TP-2M Aluminum Ranging Pole dengan panjang 2m dan konstruksi tahan lama. Spike steel, graduasi presisi, cocok untuk survei topografi.'),

('South Telescopic Ranging Pole', 'south-telescopic-ranging-pole', 
'Ranging pole teleskopik South dengan panjang adjustable 1.8m - 3.6m dan diameter 25mm. Dilengkapi dengan graduasi merah-putih setiap 10cm dan sistem locking yang kuat. Ujung bawah dengan spike steel dan ujung atas dengan thread 5/8". Konstruksi aluminum dengan berat 1.8kg. Cocok untuk survei dengan ketinggian bervariasi dan aplikasi fleksibel.', 
'Ranging pole teleskopik adjustable 1.8m - 3.6m', 
'SOU-TELE-POLE', 1299000, 1499000, 1000000, 
7, 11, true, true, true, 30, 1.8, 
'{"panjang": "180-360 cm", "diameter": "25 mm"}', 
'["/images/products/south-telescopic-1.jpg", "/images/products/south-telescopic-2.jpg"]', 
'["ranging pole", "teleskopik", "adjustable", "sistem locking", "survei", "fleksibel"]', 
'South Telescopic Ranging Pole - Ranging Pole Teleskopik 1.8m-3.6m | Fleksibel', 
'Beli South Telescopic Ranging Pole dengan panjang adjustable 1.8m-3.6m. Sistem locking kuat, spike steel, cocok untuk survei dengan ketinggian bervariasi.'),

-- Prisma Reflektor Products
('Leica GPR1 Circular Prism', 'leica-gpr1-circular-prism', 
'Prisma reflector Leica GPR1 dengan diameter 62mm dan konstanta prisma 0mm. Dilengkapi dengan Leica coating technology untuk refleksi optimal. Akurasi tinggi dengan deviasi <2 arc second. Konstruksi metal housing yang tahan lama. Cocok untuk survei dengan total station, EDM, dan aplikasi pengukuran jarak presisi tinggi.', 
'Prisma reflector circular 62mm dengan konstanta 0mm', 
'LEI-GPR1-PRISM', 4599000, 4999000, 3700000, 
8, 3, true, true, true, 25, 0.4, 
'{"diameter": "62 mm", "tinggi": "45 mm"}', 
'["/images/products/leica-gpr1-1.jpg", "/images/products/leica-gpr1-2.jpg"]', 
'["prisma reflector", "circular", "konstanta 0mm", "coating technology", "total station", "EDM", "presisi tinggi"]', 
'Leica GPR1 Circular Prism - Prisma Reflector dengan Konstanta 0mm | Jual Leica', 
'Beli Leica GPR1 Circular Prism dengan diameter 62mm dan konstanta 0mm. Coating technology, akurasi tinggi, cocok untuk survei dengan total station.'),

('Topcon AP-O1 All Weather Prism', 'topcon-ap-o1-all-weather-prism', 
'Prisma reflector Topcon AP-O1 dengan diameter 62mm dan konstanta prisma -30mm. Dilengkapi dengan all-weather coating untuk kondisi cuaca ekstrem. Akurasi tinggi dengan deviasi <3 arc second. Konstruksi bronze housing yang tahan korosi. Cocok untuk survei outdoor, monitoring, dan aplikasi pengukuran dalam kondisi cuaca sulit.', 
'Prisma reflector all-weather dengan konstanta -30mm', 
'TOP-APO1-PRISM', 3699000, 3999000, 2900000, 
8, 4, true, false, true, 35, 0.5, 
'{"diameter": "62 mm", "tinggi": "48 mm"}', 
'["/images/products/topcon-ap-o1-1.jpg", "/images/products/topcon-ap-o1-2.jpg"]', 
'["prisma reflector", "all-weather", "konstanta -30mm", "coating", "survei outdoor", "monitoring", "cuaca ekstrem"]', 
'Topcon AP-O1 All Weather Prism - Prisma Reflector untuk Cuaca Ekstrem', 
'Jual Topcon AP-O1 All Weather Prism dengan diameter 62mm dan konstanta -30mm. All-weather coating, tahan korosi, cocok untuk survei outdoor.'),

('Sokkia AP41 360° Prism', 'sokkia-ap41-360-prism', 
'Prisma reflector Sokkia AP41 dengan teknologi 360° reflection dan konstanta prisma -30mm. Dilengkapi dengan tilt mechanism untuk adjustment yang mudah. Akurasi tinggi dengan deviasi <5 arc second. Konstruksi metal housing yang robust. Cocok untuk survei dengan total station robotik, monitoring, dan aplikasi yang membutuhkan fleksibilitas sudut pengukuran.', 
'Prisma reflector 360° dengan tilt mechanism', 
'SOK-AP41-PRISM', 2999000, 3299000, 2300000, 
8, 5, true, true, true, 28, 0.6, 
'{"diameter": "62 mm", "tinggi": "52 mm"}', 
'["/images/products/sokkia-ap41-1.jpg", "/images/products/sokkia-ap41-2.jpg"]', 
'["prisma reflector", "360 derajat", "tilt mechanism", "total station robotik", "monitoring", "fleksibilitas sudut"]', 
'Sokkia AP41 360° Prism - Prisma Reflector dengan Teknologi 360° Reflection', 
'Beli Sokkia AP41 360° Prism dengan teknologi 360° reflection dan tilt mechanism. Konstanta -30mm, robust housing, cocok untuk total station robotik.'),

-- GPS Mapping Products
('Garmin Montana 750i', 'garmin-montana-750i', 
'GPS mapping Garmin Montana 750i dengan layar touchscreen 5" dan teknologi inReach satellite. Dilengkapi dengan kamera 8MP dan kemampuan geotagging. Peta TopoActive preloaded dengan slot microSD untuk ekspansi. Tahan air IPX7 dengan baterai Li-ion hingga 18 jam. Cocok untuk mapping, surveying, dan aplikasi GIS mobile yang membutuhkan komunikasi satelit.', 
'GPS mapping dengan layar 5" dan teknologi inReach', 
'GAR-MONTANA-750I', 12999000, 13999000, 10500000, 
9, 1, true, true, true, 20, 0.35, 
'{"panjang": "7.5 cm", "lebar": "14.2 cm", "tinggi": "3.6 cm"}', 
'["/images/products/garmin-montana-750i-1.jpg", "/images/products/garmin-montana-750i-2.jpg"]', 
'["GPS mapping", "layar 5 inci", "inReach", "kamera 8MP", "geotagging", "mapping", "surveying", "GIS mobile"]', 
'Garmin Montana 750i - GPS Mapping dengan Layar 5" dan inReach | Jual Garmin', 
'Beli Garmin Montana 750i GPS mapping dengan layar touchscreen 5" dan teknologi inReach. Kamera 8MP, geotagging, IPX7, cocok untuk mapping dan surveying.'),

('Trimble Juno 5 Series', 'trimble-juno-5-series', 
'GPS mapping Trimble Juno 5 Series dengan teknologi GNSS dan akurasi sub-meter. Dilengkapi dengan Windows Mobile OS dan kamera 5MP. Layar touchscreen 4.3" dengan keyboard fisik. Tahan air IP65 dengan baterai hingga 12 jam. Cocok untuk GIS data collection, asset management, dan aplikasi mapping profesional yang membutuhkan akurasi tinggi.', 
'GPS mapping dengan akurasi sub-meter dan Windows Mobile', 
'TRI-JUNO5-MAP', 24999000, 26999000, 20000000, 
9, 2, true, false, true, 15, 0.45, 
'{"panjang": "8.2 cm", "lebar": "17.8 cm", "tinggi": "3.2 cm"}', 
'["/images/products/trimble-juno-5-1.jpg", "/images/products/trimble-juno-5-2.jpg"]', 
'["GPS mapping", "akurasi sub-meter", "Windows Mobile", "kamera 5MP", "GIS data collection", "asset management"]', 
'Trimble Juno 5 Series - GPS Mapping dengan Akurasi Sub-Meter | Jual Trimble', 
'Beli Trimble Juno 5 Series GPS mapping dengan akurasi sub-meter dan Windows Mobile OS. Kamera 5MP, IP65, cocok untuk GIS data collection.'),

-- Software Survei Products
('Leica Captivate Software', 'leica-captivate-software', 
'Software survei Leica Captivate dengan antarmuka 3D dan workflow yang intuitif. Dilengkapi dengan fitur CAD, stakeout, dan data management. Kompatibel dengan semua instrumen Leica. Fitur cloud connectivity untuk sinkronisasi data real-time. Cocok untuk survei konstruksi, engineering, dan aplikasi profesional yang membutuhkan efficiency dan accuracy.', 
'Software survei 3D dengan workflow intuitif', 
'LEI-CAPTIVATE-SW', 15999000, 17999000, 12000000, 
10, 3, true, true, true, 100, 0.1, 
'{"format": "Digital Download", "platform": "Windows/Android"}', 
'["/images/products/leica-captivate-1.jpg", "/images/products/leica-captivate-2.jpg"]', 
'["software survei", "3D", "workflow intuitif", "CAD", "stakeout", "cloud connectivity", "survei konstruksi"]', 
'Leica Captivate Software - Software Survei 3D dengan Workflow Intuitif', 
'Beli Leica Captivate Software dengan antarmuka 3D dan workflow intuitif. Fitur CAD, stakeout, cloud connectivity, cocok untuk survei konstruksi.'),

('Topcon MAGNET Field Software', 'topcon-magnet-field-software', 
'Software survei Topcon MAGNET Field dengan kemampuan data collection dan stakeout yang komprehensif. Dilengkapi dengan fitur CAD, mapping, dan road design. Kompatibel dengan semua instrumen Topcon. Interface yang user-friendly dengan customizable workflow. Cocok untuk survei konstruksi, cadastral, dan aplikasi engineering yang membutuhkan flexibility dan precision.', 
'Software survei dengan data collection dan stakeout komprehensif', 
'TOP-MAGNET-SW', 12999000, 14999000, 10000000, 
10, 4, true, false, true, 100, 0.1, 
'{"format": "Digital Download", "platform": "Windows/Android"}', 
'["/images/products/topcon-magnet-1.jpg", "/images/products/topcon-magnet-2.jpg"]', 
'["software survei", "data collection", "stakeout", "CAD", "mapping", "road design", "survei konstruksi"]', 
'Topcon MAGNET Field Software - Software Survei dengan Data Collection Komprehensif', 
'Beli Topcon MAGNET Field Software dengan kemampuan data collection dan stakeout. Fitur CAD, mapping, road design, cocok untuk survei konstruksi.'),

('Carlson SurvCE Software', 'carlson-survce-software', 
'Software survei Carlson SurvCE dengan fitur data collection, stakeout, dan COGO calculations. Dilengkapi dengan road design, volume calculations, dan mapping tools. Kompatibel dengan berbagai instrumen survei. Interface yang mudah digunakan dengan extensive help system. Cocok untuk survei topografi, construction layout, dan aplikasi engineering dengan harga terjangkau.', 
'Software survei dengan COGO calculations dan road design', 
'CAR-SURVCE-SW', 8999000, 9999000, 7000000, 
10, 10, true, true, true, 100, 0.1, 
'{"format": "Digital Download", "platform": "Windows Mobile"}', 
'["/images/products/carlson-survce-1.jpg", "/images/products/carlson-survce-2.jpg"]', 
'["software survei", "COGO calculations", "road design", "volume calculations", "mapping tools", "survei topografi"]', 
'Carlson SurvCE Software - Software Survei dengan COGO Calculations', 
'Beli Carlson SurvCE Software dengan fitur COGO calculations dan road design. Volume calculations, mapping tools, harga terjangkau, cocok untuk survei topografi.');

-- Add product attributes for the first few products
INSERT INTO product_attributes (product_id, name, value) VALUES
(1, 'Akurasi', '3 meter (95% typical)'),
(1, 'Satelit', 'GPS, GLONASS, Galileo, QZSS'),
(1, 'Layar', '3 inci, 240 x 400 piksel'),
(1, 'Baterai', 'Li-ion, 35 jam (mode GPS)'),
(1, 'Memori', '16 GB internal'),
(1, 'Konektivitas', 'Bluetooth, Wi-Fi, USB'),
(1, 'Sertifikasi', 'IPX7 (tahan air)'),

(2, 'Akurasi', '3 meter (95% typical)'),
(2, 'Satelit', 'GPS, GLONASS'),
(2, 'Layar', '2.2 inci, 240 x 320 piksel'),
(2, 'Baterai', '2 x AA, 25 jam'),
(2, 'Memori', '8 GB internal + microSD'),
(2, 'Sensor', 'Kompas 3-axis, Barometer'),
(2, 'Sertifikasi', 'IPX7 (tahan air)'),

(3, 'Akurasi', '3 meter (95% typical)'),
(3, 'Satelit', 'GPS, GLONASS, Galileo'),
(3, 'Layar', '2.6 inci, 160 x 240 piksel'),
(3, 'Baterai', '2 x AA, 16 jam'),
(3, 'Memori', '8 GB internal + microSD'),
(3, 'Sensor', 'Kompas 3-axis, Barometer, Altimeter'),
(3, 'Sertifikasi', 'IPX7 (tahan air)'),

(4, 'Akurasi', '3 meter (95% typical)'),
(4, 'Satelit', 'GPS, GLONASS'),
(4, 'Layar', '3 inci touchscreen'),
(4, 'Baterai', 'Li-ion, 18 jam'),
(4, 'Kamera', '3.2 MP dengan geotagging'),
(4, 'Memori', '2 GB internal + microSD'),
(4, 'Sertifikasi', 'IPX7 (tahan air)'),

(5, 'Akurasi', '3 mm + 0.1 ppm (horizontal)'),
(5, 'Satelit', 'GPS, GLONASS, Galileo, BeiDou, QZSS'),
(5, 'Teknologi', 'Maxwell 7 GNSS chip'),
(5, 'IMU', 'Integrated inertial measurement unit'),
(5, 'Konektivitas', 'Bluetooth, Wi-Fi, UHF radio'),
(5, 'Baterai', 'Li-ion, 4 jam (tracking mode)'),
(5, 'Sertifikasi', 'IP68 (tahan air dan debu)');

-- Add some product reviews
INSERT INTO product_reviews (product_id, user_id, rating, title, comment, is_verified, is_approved) VALUES
(1, 1, 5, 'GPS terbaik untuk hiking', 'Sangat puas dengan performa Garmin GPSMAP 66i. Fitur InReach sangat membantu saat hiking di area terpencil. Baterai tahan lama dan akurasi GPS sangat baik.', true, true),
(1, 2, 4, 'Fitur lengkap tapi mahal', 'GPS dengan fitur sangat lengkap, terutama komunikasi satelit. Harga memang mahal tapi sebanding dengan fitur yang didapat. Layar jelas dan mudah digunakan.', true, true),
(2, 3, 5, 'Value for money terbaik', 'Garmin eTrex 32x memberikan value yang sangat baik. Peta TopoActive sangat membantu untuk hiking. Baterai AA mudah diganti dan tahan lama.', true, true),
(3, 4, 4, 'Multi-GNSS sangat akurat', 'Dukungan multi-GNSS membuat akurasi posisi sangat baik. Sensor kompas dan barometer bekerja dengan baik. Cocok untuk outdoor adventure.', true, true),
(5, 5, 5, 'GNSS receiver terbaik', 'Trimble R12i memberikan akurasi yang luar biasa. IMU terintegrasi sangat membantu dalam survei. Investasi yang sangat worthit untuk pekerjaan survei profesional.', true, true);
